// The rest of each city's catalogue: ten more restaurants per city, added
// alongside #103 so the home feed reads like a real delivery app rather than
// a four-card demo. Same shape and rules as restaurants.ts: invented names,
// no real chain's, prices in minor units (USD cents / whole đồng), every
// image a real, licence-clean download fetched through docs/design/
// photos.json (#106) - see docs/design/80-photo-credits.md for credits.

import type { Restaurant } from './restaurants';

export const SF_MORE: Restaurant[] = [
  {
    slug: 'dogpatch-burger-works',
    name: 'Dogpatch Burger Works',
    city: 'sf',
    cuisineTag: 'Burgers',
    rating: 4.6,
    reviewCount: 1102,
    deliveryFeeMinor: 199,
    hasDeal: true,
    heroImage: '/images/restaurants/dogpatch-burger-works-hero.jpg',
    menu: [
      {
        title: 'Burgers',
        items: [
          {
            id: 'dogpatch-burger-works-classic-cheeseburger',
            name: 'Classic cheeseburger',
            description: 'Grass-fed beef, cheddar, pickles, house sauce.',
            amountMinor: 1450,
            image: '/images/dishes/dogpatch-burger-works-classic-cheeseburger.jpg',
          },
          {
            id: 'dogpatch-burger-works-mushroom-swiss-burger',
            name: 'Mushroom swiss burger',
            description: 'Beef patty, roasted mushrooms, swiss, garlic aioli.',
            amountMinor: 1595,
            image: '/images/dishes/dogpatch-burger-works-mushroom-swiss-burger.jpg',
          },
          {
            id: 'dogpatch-burger-works-crispy-chicken-sandwich',
            name: 'Crispy chicken sandwich',
            description: 'Buttermilk fried chicken, slaw, pickles, spicy mayo.',
            amountMinor: 1525,
            image: '/images/dishes/dogpatch-burger-works-crispy-chicken-sandwich.jpg',
          },
        ],
      },
      {
        title: 'Sides & drinks',
        items: [
          {
            id: 'dogpatch-burger-works-garlic-fries',
            name: 'Garlic fries',
            description: 'Hand-cut fries, garlic, parsley, sea salt.',
            amountMinor: 675,
            image: '/images/dishes/dogpatch-burger-works-garlic-fries.jpg',
          },
          {
            id: 'dogpatch-burger-works-vanilla-milkshake',
            name: 'Vanilla milkshake',
            description: 'Vanilla bean ice cream, whole milk, whipped cream.',
            amountMinor: 750,
            image: '/images/dishes/dogpatch-burger-works-vanilla-milkshake.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'noriega-thai-kitchen',
    name: 'Noriega Thai Kitchen',
    city: 'sf',
    cuisineTag: 'Thai',
    rating: 4.7,
    reviewCount: 2450,
    deliveryFeeMinor: 149,
    hasDeal: false,
    heroImage: '/images/restaurants/noriega-thai-kitchen-hero.jpg',
    menu: [
      {
        title: 'Mains',
        items: [
          {
            id: 'noriega-thai-kitchen-pad-see-ew',
            name: 'Pad see ew',
            description: 'Wide rice noodles, chicken, Chinese broccoli, egg.',
            amountMinor: 1695,
            image: '/images/dishes/noriega-thai-kitchen-pad-see-ew.jpg',
          },
          {
            id: 'noriega-thai-kitchen-green-curry',
            name: 'Green curry',
            description: 'Coconut milk, bamboo shoots, Thai basil, chicken.',
            amountMinor: 1750,
            image: '/images/dishes/noriega-thai-kitchen-green-curry.jpg',
          },
          {
            id: 'noriega-thai-kitchen-pad-kra-pao',
            name: 'Pad kra pao',
            description: 'Minced pork, holy basil, chili, fried egg.',
            amountMinor: 1650,
            image: '/images/dishes/noriega-thai-kitchen-pad-kra-pao.jpg',
          },
          {
            id: 'noriega-thai-kitchen-khao-soi',
            name: 'Khao soi',
            description: 'Egg noodles, curry broth, braised chicken, shallots.',
            amountMinor: 1850,
            image: '/images/dishes/noriega-thai-kitchen-khao-soi.jpg',
          },
        ],
      },
      {
        title: 'Sides & drinks',
        items: [
          {
            id: 'noriega-thai-kitchen-fresh-spring-rolls',
            name: 'Fresh spring rolls',
            description: 'Rice paper, shrimp, mint, peanut dipping sauce.',
            amountMinor: 795,
            image: '/images/dishes/noriega-thai-kitchen-fresh-spring-rolls.jpg',
          },
          {
            id: 'noriega-thai-kitchen-thai-iced-tea',
            name: 'Thai iced tea',
            description: 'Black tea, spices, sweetened condensed milk.',
            amountMinor: 525,
            image: '/images/dishes/noriega-thai-kitchen-thai-iced-tea.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'inner-richmond-sushi-bar',
    name: 'Inner Richmond Sushi Bar',
    city: 'sf',
    cuisineTag: 'Sushi',
    rating: 4.8,
    reviewCount: 3312,
    deliveryFeeMinor: 249,
    hasDeal: false,
    heroImage: '/images/restaurants/inner-richmond-sushi-bar-hero.jpg',
    menu: [
      {
        title: 'Rolls & plates',
        items: [
          {
            id: 'inner-richmond-sushi-bar-spicy-tuna-roll',
            name: 'Spicy tuna roll',
            description: 'Bigeye tuna, spicy mayo, cucumber, sesame.',
            amountMinor: 1395,
            image: '/images/dishes/inner-richmond-sushi-bar-spicy-tuna-roll.jpg',
          },
          {
            id: 'inner-richmond-sushi-bar-salmon-avocado-roll',
            name: 'Salmon avocado roll',
            description: 'King salmon, avocado, sushi rice, nori.',
            amountMinor: 1350,
            image: '/images/dishes/inner-richmond-sushi-bar-salmon-avocado-roll.jpg',
          },
          {
            id: 'inner-richmond-sushi-bar-chirashi-bowl',
            name: 'Chirashi bowl',
            description: 'Assorted sashimi, tamago, pickled ginger, sushi rice.',
            amountMinor: 2495,
            image: '/images/dishes/inner-richmond-sushi-bar-chirashi-bowl.jpg',
          },
          {
            id: 'inner-richmond-sushi-bar-nigiri-set',
            name: 'Nigiri set',
            description: 'Eight pieces, chef\'s selection, wasabi, ginger.',
            amountMinor: 2600,
            image: '/images/dishes/inner-richmond-sushi-bar-nigiri-set.jpg',
          },
        ],
      },
      {
        title: 'Sides',
        items: [
          {
            id: 'inner-richmond-sushi-bar-miso-soup',
            name: 'Miso soup',
            description: 'White miso, tofu, wakame, scallions.',
            amountMinor: 400,
            image: '/images/dishes/inner-richmond-sushi-bar-miso-soup.jpg',
          },
          {
            id: 'inner-richmond-sushi-bar-seaweed-salad',
            name: 'Seaweed salad',
            description: 'Marinated wakame, sesame oil, toasted sesame seeds.',
            amountMinor: 595,
            image: '/images/dishes/inner-richmond-sushi-bar-seaweed-salad.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'valencia-street-tandoor',
    name: 'Valencia Street Tandoor',
    city: 'sf',
    cuisineTag: 'Indian',
    rating: 4.5,
    reviewCount: 615,
    deliveryFeeMinor: 0,
    hasDeal: true,
    heroImage: '/images/restaurants/valencia-street-tandoor-hero.jpg',
    menu: [
      {
        title: 'Curries & tandoor',
        items: [
          {
            id: 'valencia-street-tandoor-chicken-tikka-masala',
            name: 'Chicken tikka masala',
            description: 'Charred chicken, tomato cream sauce, fenugreek.',
            amountMinor: 1895,
            image: '/images/dishes/valencia-street-tandoor-chicken-tikka-masala.jpg',
          },
          {
            id: 'valencia-street-tandoor-saag-paneer',
            name: 'Saag paneer',
            description: 'Spinach, fresh paneer, garlic, ginger, cumin.',
            amountMinor: 1695,
            image: '/images/dishes/valencia-street-tandoor-saag-paneer.jpg',
          },
          {
            id: 'valencia-street-tandoor-lamb-rogan-josh',
            name: 'Lamb rogan josh',
            description: 'Slow-cooked lamb, Kashmiri chili, yogurt, cardamom.',
            amountMinor: 2250,
            image: '/images/dishes/valencia-street-tandoor-lamb-rogan-josh.jpg',
          },
        ],
      },
      {
        title: 'Breads & drinks',
        items: [
          {
            id: 'valencia-street-tandoor-garlic-naan',
            name: 'Garlic naan',
            description: 'Tandoor-baked flatbread, garlic, butter, cilantro.',
            amountMinor: 450,
            image: '/images/dishes/valencia-street-tandoor-garlic-naan.jpg',
          },
          {
            id: 'valencia-street-tandoor-mango-lassi',
            name: 'Mango lassi',
            description: 'Alphonso mango, yogurt, cardamom.',
            amountMinor: 575,
            image: '/images/dishes/valencia-street-tandoor-mango-lassi.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'cole-valley-mezze',
    name: 'Cole Valley Mezze',
    city: 'sf',
    cuisineTag: 'Mediterranean',
    rating: 4.4,
    reviewCount: 389,
    deliveryFeeMinor: 99,
    hasDeal: false,
    heroImage: '/images/restaurants/cole-valley-mezze-hero.jpg',
    menu: [
      {
        title: 'Plates',
        items: [
          {
            id: 'cole-valley-mezze-chicken-shawarma-plate',
            name: 'Chicken shawarma plate',
            description: 'Spiced chicken, rice, hummus, pickled turnips.',
            amountMinor: 1795,
            image: '/images/dishes/cole-valley-mezze-chicken-shawarma-plate.jpg',
          },
          {
            id: 'cole-valley-mezze-falafel-wrap',
            name: 'Falafel wrap',
            description: 'Crispy falafel, tahini, tomato, cucumber, lavash.',
            amountMinor: 1395,
            image: '/images/dishes/cole-valley-mezze-falafel-wrap.jpg',
          },
          {
            id: 'cole-valley-mezze-lamb-kofta-bowl',
            name: 'Lamb kofta bowl',
            description: 'Grilled lamb kofta, tabbouleh, tzatziki, freekeh.',
            amountMinor: 1975,
            image: '/images/dishes/cole-valley-mezze-lamb-kofta-bowl.jpg',
          },
        ],
      },
      {
        title: 'Sides & drinks',
        items: [
          {
            id: 'cole-valley-mezze-hummus-and-pita',
            name: 'Hummus and pita',
            description: 'Chickpeas, tahini, olive oil, warm pita.',
            amountMinor: 750,
            image: '/images/dishes/cole-valley-mezze-hummus-and-pita.jpg',
          },
          {
            id: 'cole-valley-mezze-mint-lemonade',
            name: 'Mint lemonade',
            description: 'Fresh lemon, mint, cane sugar.',
            amountMinor: 500,
            image: '/images/dishes/cole-valley-mezze-mint-lemonade.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'geary-boulevard-korean-kitchen',
    name: 'Geary Boulevard Korean Kitchen',
    city: 'sf',
    cuisineTag: 'Korean',
    rating: 4.7,
    reviewCount: 1734,
    deliveryFeeMinor: 199,
    hasDeal: true,
    heroImage: '/images/restaurants/geary-boulevard-korean-kitchen-hero.jpg',
    menu: [
      {
        title: 'Mains',
        items: [
          {
            id: 'geary-boulevard-korean-kitchen-dolsot-bibimbap',
            name: 'Dolsot bibimbap',
            description: 'Rice, sautéed vegetables, beef, fried egg, gochujang.',
            amountMinor: 1895,
            image: '/images/dishes/geary-boulevard-korean-kitchen-dolsot-bibimbap.jpg',
          },
          {
            id: 'geary-boulevard-korean-kitchen-beef-bulgogi',
            name: 'Beef bulgogi',
            description: 'Marinated ribeye, onion, scallion, steamed rice.',
            amountMinor: 2250,
            image: '/images/dishes/geary-boulevard-korean-kitchen-beef-bulgogi.jpg',
          },
          {
            id: 'geary-boulevard-korean-kitchen-kimchi-jjigae',
            name: 'Kimchi jjigae',
            description: 'Aged kimchi, pork belly, tofu, spicy broth.',
            amountMinor: 1750,
            image: '/images/dishes/geary-boulevard-korean-kitchen-kimchi-jjigae.jpg',
          },
        ],
      },
      {
        title: 'Sides',
        items: [
          {
            id: 'geary-boulevard-korean-kitchen-seafood-pancake',
            name: 'Seafood pancake',
            description: 'Crispy scallion batter, squid, shrimp, dipping sauce.',
            amountMinor: 1450,
            image: '/images/dishes/geary-boulevard-korean-kitchen-seafood-pancake.jpg',
          },
          {
            id: 'geary-boulevard-korean-kitchen-barley-tea',
            name: 'Barley tea',
            description: 'Roasted barley, served iced, lightly nutty.',
            amountMinor: 350,
            image: '/images/dishes/geary-boulevard-korean-kitchen-barley-tea.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'post-street-ramen-bar',
    name: 'Post Street Ramen Bar',
    city: 'sf',
    cuisineTag: 'Ramen',
    rating: 4.6,
    reviewCount: 1288,
    deliveryFeeMinor: 249,
    hasDeal: false,
    heroImage: '/images/restaurants/post-street-ramen-bar-hero.jpg',
    menu: [
      {
        title: 'Ramen',
        items: [
          {
            id: 'post-street-ramen-bar-tonkotsu-ramen',
            name: 'Tonkotsu ramen',
            description: 'Pork bone broth, chashu, soft egg, scallion.',
            amountMinor: 1795,
            image: '/images/dishes/post-street-ramen-bar-tonkotsu-ramen.jpg',
          },
          {
            id: 'post-street-ramen-bar-spicy-miso-ramen',
            name: 'Spicy miso ramen',
            description: 'Miso broth, ground pork, corn, chili oil.',
            amountMinor: 1850,
            image: '/images/dishes/post-street-ramen-bar-spicy-miso-ramen.jpg',
          },
          {
            id: 'post-street-ramen-bar-shoyu-chicken-ramen',
            name: 'Shoyu chicken ramen',
            description: 'Soy chicken broth, chicken chashu, bamboo, nori.',
            amountMinor: 1695,
            image: '/images/dishes/post-street-ramen-bar-shoyu-chicken-ramen.jpg',
          },
        ],
      },
      {
        title: 'Sides',
        items: [
          {
            id: 'post-street-ramen-bar-pork-gyoza',
            name: 'Pork gyoza',
            description: 'Pan-fried dumplings, pork, cabbage, ponzu.',
            amountMinor: 795,
            image: '/images/dishes/post-street-ramen-bar-pork-gyoza.jpg',
          },
          {
            id: 'post-street-ramen-bar-chicken-karaage',
            name: 'Chicken karaage',
            description: 'Crispy fried chicken thigh, lemon, kewpie mayo.',
            amountMinor: 850,
            image: '/images/dishes/post-street-ramen-bar-chicken-karaage.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'noe-valley-morning-kitchen',
    name: 'Noe Valley Morning Kitchen',
    city: 'sf',
    cuisineTag: 'Breakfast',
    rating: 4.5,
    reviewCount: 872,
    deliveryFeeMinor: 0,
    hasDeal: false,
    heroImage: '/images/restaurants/noe-valley-morning-kitchen-hero.jpg',
    menu: [
      {
        title: 'Plates',
        items: [
          {
            id: 'noe-valley-morning-kitchen-buttermilk-pancakes',
            name: 'Buttermilk pancakes',
            description: 'Three pancakes, whipped butter, maple syrup, berries.',
            amountMinor: 1450,
            image: '/images/dishes/noe-valley-morning-kitchen-buttermilk-pancakes.jpg',
          },
          {
            id: 'noe-valley-morning-kitchen-dungeness-crab-benedict',
            name: 'Dungeness crab benedict',
            description: 'English muffin, crab, poached eggs, hollandaise.',
            amountMinor: 2395,
            image: '/images/dishes/noe-valley-morning-kitchen-dungeness-crab-benedict.jpg',
          },
          {
            id: 'noe-valley-morning-kitchen-breakfast-burrito',
            name: 'Breakfast burrito',
            description: 'Scrambled eggs, bacon, potatoes, cheddar, salsa.',
            amountMinor: 1375,
            image: '/images/dishes/noe-valley-morning-kitchen-breakfast-burrito.jpg',
          },
          {
            id: 'noe-valley-morning-kitchen-avocado-toast',
            name: 'Avocado toast',
            description: 'Sourdough, smashed avocado, radish, chili flakes.',
            amountMinor: 1250,
            image: '/images/dishes/noe-valley-morning-kitchen-avocado-toast.jpg',
          },
        ],
      },
      {
        title: 'Drinks',
        items: [
          {
            id: 'noe-valley-morning-kitchen-fresh-orange-juice',
            name: 'Fresh orange juice',
            description: 'Freshly squeezed Valencia oranges, no added sugar.',
            amountMinor: 595,
            image: '/images/dishes/noe-valley-morning-kitchen-fresh-orange-juice.jpg',
          },
          {
            id: 'noe-valley-morning-kitchen-oat-milk-latte',
            name: 'Oat milk latte',
            description: 'Double espresso, steamed oat milk.',
            amountMinor: 550,
            image: '/images/dishes/noe-valley-morning-kitchen-oat-milk-latte.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'hayes-valley-green-table',
    name: 'Hayes Valley Green Table',
    city: 'sf',
    cuisineTag: 'Vegan',
    rating: 4.4,
    reviewCount: 456,
    deliveryFeeMinor: 149,
    hasDeal: true,
    heroImage: '/images/restaurants/hayes-valley-green-table-hero.jpg',
    menu: [
      {
        title: 'Mains',
        items: [
          {
            id: 'hayes-valley-green-table-mushroom-tacos',
            name: 'Mushroom tacos',
            description: 'Roasted oyster mushrooms, cashew crema, pickled onion.',
            amountMinor: 1550,
            image: '/images/dishes/hayes-valley-green-table-mushroom-tacos.jpg',
          },
          {
            id: 'hayes-valley-green-table-tofu-banh-mi',
            name: 'Tofu banh mi',
            description: 'Lemongrass tofu, pickled carrot, cilantro, vegan mayo.',
            amountMinor: 1395,
            image: '/images/dishes/hayes-valley-green-table-tofu-banh-mi.jpg',
          },
          {
            id: 'hayes-valley-green-table-chickpea-curry',
            name: 'Chickpea curry',
            description: 'Coconut curry, chickpeas, spinach, brown rice.',
            amountMinor: 1650,
            image: '/images/dishes/hayes-valley-green-table-chickpea-curry.jpg',
          },
        ],
      },
      {
        title: 'Sides & drinks',
        items: [
          {
            id: 'hayes-valley-green-table-sweet-potato-fries',
            name: 'Sweet potato fries',
            description: 'Crispy sweet potato, smoked paprika, garlic aioli.',
            amountMinor: 695,
            image: '/images/dishes/hayes-valley-green-table-sweet-potato-fries.jpg',
          },
          {
            id: 'hayes-valley-green-table-green-smoothie',
            name: 'Green smoothie',
            description: 'Kale, banana, mango, almond milk, dates.',
            amountMinor: 775,
            image: '/images/dishes/hayes-valley-green-table-green-smoothie.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'ocean-beach-fish-house',
    name: 'Ocean Beach Fish House',
    city: 'sf',
    cuisineTag: 'Seafood',
    rating: 4.8,
    reviewCount: 2967,
    deliveryFeeMinor: 299,
    hasDeal: false,
    heroImage: '/images/restaurants/ocean-beach-fish-house-hero.jpg',
    menu: [
      {
        title: 'Mains',
        items: [
          {
            id: 'ocean-beach-fish-house-fish-and-chips',
            name: 'Fish and chips',
            description: 'Beer-battered rock cod, fries, tartar sauce.',
            amountMinor: 1995,
            image: '/images/dishes/ocean-beach-fish-house-fish-and-chips.jpg',
          },
          {
            id: 'ocean-beach-fish-house-cioppino',
            name: 'Cioppino',
            description: 'Tomato broth, crab, clams, mussels, sourdough.',
            amountMinor: 2795,
            image: '/images/dishes/ocean-beach-fish-house-cioppino.jpg',
          },
          {
            id: 'ocean-beach-fish-house-grilled-salmon-plate',
            name: 'Grilled salmon plate',
            description: 'King salmon, lemon butter, greens, roasted potatoes.',
            amountMinor: 2650,
            image: '/images/dishes/ocean-beach-fish-house-grilled-salmon-plate.jpg',
          },
        ],
      },
      {
        title: 'Sides',
        items: [
          {
            id: 'ocean-beach-fish-house-clam-chowder',
            name: 'Clam chowder',
            description: 'Creamy clams, potato, bacon, oyster crackers.',
            amountMinor: 795,
            image: '/images/dishes/ocean-beach-fish-house-clam-chowder.jpg',
          },
          {
            id: 'ocean-beach-fish-house-garlic-sourdough',
            name: 'Garlic sourdough',
            description: 'Toasted sourdough, garlic butter, parsley.',
            amountMinor: 450,
            image: '/images/dishes/ocean-beach-fish-house-garlic-sourdough.jpg',
          },
        ],
      },
    ],
  },
];

export const HCMC_MORE: Restaurant[] = [
  {
    slug: 'hu-tieu-nam-vang-hoa-phat',
    name: 'Hủ Tiếu Nam Vang Hòa Phát',
    city: 'hcmc',
    cuisineTag: 'Hủ tiếu',
    rating: 4.6,
    reviewCount: 1421,
    deliveryFeeMinor: 12000,
    hasDeal: true,
    heroImage: '/images/restaurants/hu-tieu-nam-vang-hoa-phat-hero.jpg',
    menu: [
      {
        title: 'Noodles',
        items: [
          {
            id: 'hu-tieu-nam-vang-hoa-phat-hu-tieu-nam-vang',
            name: 'Hủ tiếu Nam Vang',
            description: 'Clear pork broth, shrimp, minced pork, quail egg.',
            amountMinor: 60000,
            image: '/images/dishes/hu-tieu-nam-vang-hoa-phat-hu-tieu-nam-vang.jpg',
          },
          {
            id: 'hu-tieu-nam-vang-hoa-phat-hu-tieu-kho',
            name: 'Hủ tiếu khô',
            description: 'Dry noodles, sweet soy glaze, shrimp, broth aside.',
            amountMinor: 60000,
            image: '/images/dishes/hu-tieu-nam-vang-hoa-phat-hu-tieu-kho.jpg',
          },
          {
            id: 'hu-tieu-nam-vang-hoa-phat-hu-tieu-muc',
            name: 'Hủ tiếu mực',
            description: 'Squid, clear broth, chives, fried garlic.',
            amountMinor: 70000,
            image: '/images/dishes/hu-tieu-nam-vang-hoa-phat-hu-tieu-muc.jpg',
          },
          {
            id: 'hu-tieu-nam-vang-hoa-phat-mi-hoanh-thanh',
            name: 'Mì hoành thánh',
            description: 'Egg noodles, pork wontons, bok choy, broth.',
            amountMinor: 55000,
            image: '/images/dishes/hu-tieu-nam-vang-hoa-phat-mi-hoanh-thanh.jpg',
          },
        ],
      },
      {
        title: 'Drinks',
        items: [
          {
            id: 'hu-tieu-nam-vang-hoa-phat-tra-tac',
            name: 'Trà tắc',
            description: 'Iced tea with kumquat and honey.',
            amountMinor: 20000,
            image: '/images/dishes/hu-tieu-nam-vang-hoa-phat-tra-tac.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'goi-cuon-co-hai-cho-cu',
    name: 'Gỏi Cuốn Cô Hai Chợ Cũ',
    city: 'hcmc',
    cuisineTag: 'Gỏi cuốn',
    rating: 4.4,
    reviewCount: 528,
    deliveryFeeMinor: 10000,
    hasDeal: false,
    heroImage: '/images/restaurants/goi-cuon-co-hai-cho-cu-hero.jpg',
    menu: [
      {
        title: 'Rolls',
        items: [
          {
            id: 'goi-cuon-co-hai-cho-cu-goi-cuon-tom-thit',
            name: 'Gỏi cuốn tôm thịt',
            description: 'Shrimp, pork, vermicelli, herbs, peanut hoisin dip.',
            amountMinor: 45000,
            image: '/images/dishes/goi-cuon-co-hai-cho-cu-goi-cuon-tom-thit.jpg',
          },
          {
            id: 'goi-cuon-co-hai-cho-cu-bo-bia',
            name: 'Bò bía',
            description: 'Jicama, Chinese sausage, egg, dried shrimp.',
            amountMinor: 40000,
            image: '/images/dishes/goi-cuon-co-hai-cho-cu-bo-bia.jpg',
          },
          {
            id: 'goi-cuon-co-hai-cho-cu-bi-cuon',
            name: 'Bì cuốn',
            description: 'Shredded pork skin, toasted rice powder, herbs.',
            amountMinor: 40000,
            image: '/images/dishes/goi-cuon-co-hai-cho-cu-bi-cuon.jpg',
          },
        ],
      },
      {
        title: 'Sides & drinks',
        items: [
          {
            id: 'goi-cuon-co-hai-cho-cu-cha-gio',
            name: 'Chả giò',
            description: 'Crispy fried rolls, pork, taro, wood ear.',
            amountMinor: 50000,
            image: '/images/dishes/goi-cuon-co-hai-cho-cu-cha-gio.jpg',
          },
          {
            id: 'goi-cuon-co-hai-cho-cu-nuoc-mia',
            name: 'Nước mía',
            description: 'Fresh-pressed sugarcane juice with kumquat.',
            amountMinor: 20000,
            image: '/images/dishes/goi-cuon-co-hai-cho-cu-nuoc-mia.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'quan-lau-ut-hanh',
    name: 'Quán Lẩu Út Hạnh',
    city: 'hcmc',
    cuisineTag: 'Lẩu',
    rating: 4.7,
    reviewCount: 1876,
    deliveryFeeMinor: 18000,
    hasDeal: true,
    heroImage: '/images/restaurants/quan-lau-ut-hanh-hero.jpg',
    menu: [
      {
        title: 'Hotpots',
        items: [
          {
            id: 'quan-lau-ut-hanh-lau-thai-hai-san',
            name: 'Lẩu Thái hải sản',
            description: 'For two: sour broth, prawns, squid, mushrooms.',
            amountMinor: 290000,
            image: '/images/dishes/quan-lau-ut-hanh-lau-thai-hai-san.jpg',
          },
          {
            id: 'quan-lau-ut-hanh-lau-mam',
            name: 'Lẩu mắm',
            description: 'For two: fermented fish broth, catfish, eggplant.',
            amountMinor: 270000,
            image: '/images/dishes/quan-lau-ut-hanh-lau-mam.jpg',
          },
          {
            id: 'quan-lau-ut-hanh-lau-ga-la-e',
            name: 'Lẩu gà lá é',
            description: 'For two: chicken, lá é herb, bamboo shoots.',
            amountMinor: 250000,
            image: '/images/dishes/quan-lau-ut-hanh-lau-ga-la-e.jpg',
          },
        ],
      },
      {
        title: 'Sides & drinks',
        items: [
          {
            id: 'quan-lau-ut-hanh-nam-kim-cham-them',
            name: 'Nấm kim châm thêm',
            description: 'Extra enoki mushrooms for the hotpot.',
            amountMinor: 35000,
            image: '/images/dishes/quan-lau-ut-hanh-nam-kim-cham-them.jpg',
          },
          {
            id: 'quan-lau-ut-hanh-tra-chanh',
            name: 'Trà chanh',
            description: 'Iced black tea with fresh lime.',
            amountMinor: 20000,
            image: '/images/dishes/quan-lau-ut-hanh-tra-chanh.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'ca-phe-nha-go-18',
    name: 'Cà Phê Nhà Gỗ 18',
    city: 'hcmc',
    cuisineTag: 'Cà phê',
    rating: 4.8,
    reviewCount: 4210,
    deliveryFeeMinor: 0,
    hasDeal: false,
    heroImage: '/images/restaurants/ca-phe-nha-go-18-hero.jpg',
    menu: [
      {
        title: 'Coffee',
        items: [
          {
            id: 'ca-phe-nha-go-18-ca-phe-sua-da',
            name: 'Cà phê sữa đá',
            description: 'Robusta phin coffee, condensed milk, ice.',
            amountMinor: 30000,
            image: '/images/dishes/ca-phe-nha-go-18-ca-phe-sua-da.jpg',
          },
          {
            id: 'ca-phe-nha-go-18-ca-phe-den-da',
            name: 'Cà phê đen đá',
            description: 'Strong robusta phin coffee over ice.',
            amountMinor: 25000,
            image: '/images/dishes/ca-phe-nha-go-18-ca-phe-den-da.jpg',
          },
          {
            id: 'ca-phe-nha-go-18-bac-xiu',
            name: 'Bạc xỉu',
            description: 'Condensed milk, fresh milk, splash of coffee.',
            amountMinor: 35000,
            image: '/images/dishes/ca-phe-nha-go-18-bac-xiu.jpg',
          },
          {
            id: 'ca-phe-nha-go-18-ca-phe-muoi',
            name: 'Cà phê muối',
            description: 'Iced coffee topped with salted cream.',
            amountMinor: 35000,
            image: '/images/dishes/ca-phe-nha-go-18-ca-phe-muoi.jpg',
          },
        ],
      },
      {
        title: 'Pastries & snacks',
        items: [
          {
            id: 'ca-phe-nha-go-18-banh-bong-lan-trung-muoi',
            name: 'Bánh bông lan trứng muối',
            description: 'Sponge cake, salted egg yolk, pork floss.',
            amountMinor: 40000,
            image: '/images/dishes/ca-phe-nha-go-18-banh-bong-lan-trung-muoi.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'quan-che-di-sau',
    name: 'Quán Chè Dì Sáu',
    city: 'hcmc',
    cuisineTag: 'Chè',
    rating: 4.5,
    reviewCount: 693,
    deliveryFeeMinor: 8000,
    hasDeal: false,
    heroImage: '/images/restaurants/quan-che-di-sau-hero.jpg',
    menu: [
      {
        title: 'Sweet soups',
        items: [
          {
            id: 'quan-che-di-sau-che-thai',
            name: 'Chè Thái',
            description: 'Jackfruit, lychee, jelly, coconut milk, ice.',
            amountMinor: 40000,
            image: '/images/dishes/quan-che-di-sau-che-thai.jpg',
          },
          {
            id: 'quan-che-di-sau-che-ba-mau',
            name: 'Chè ba màu',
            description: 'Mung bean, red bean, pandan jelly, coconut.',
            amountMinor: 35000,
            image: '/images/dishes/quan-che-di-sau-che-ba-mau.jpg',
          },
          {
            id: 'quan-che-di-sau-che-chuoi-nuong',
            name: 'Chè chuối nướng',
            description: 'Grilled banana, tapioca, warm coconut sauce.',
            amountMinor: 35000,
            image: '/images/dishes/quan-che-di-sau-che-chuoi-nuong.jpg',
          },
          {
            id: 'quan-che-di-sau-suong-sa-hat-luu',
            name: 'Sương sa hạt lựu',
            description: 'Water chestnut rubies, pandan jelly, coconut milk.',
            amountMinor: 35000,
            image: '/images/dishes/quan-che-di-sau-suong-sa-hat-luu.jpg',
          },
        ],
      },
      {
        title: 'Drinks',
        items: [
          {
            id: 'quan-che-di-sau-sua-dau-nanh',
            name: 'Sữa đậu nành',
            description: 'Fresh soy milk, lightly sweetened.',
            amountMinor: 15000,
            image: '/images/dishes/quan-che-di-sau-sua-dau-nanh.jpg',
          },
          {
            id: 'quan-che-di-sau-rau-ma-dau-xanh',
            name: 'Rau má đậu xanh',
            description: 'Pennywort juice blended with mung bean.',
            amountMinor: 25000,
            image: '/images/dishes/quan-che-di-sau-rau-ma-dau-xanh.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'com-ga-ba-sau-phu-nhuan',
    name: 'Cơm Gà Bà Sáu Phú Nhuận',
    city: 'hcmc',
    cuisineTag: 'Cơm gà',
    rating: 4.6,
    reviewCount: 1345,
    deliveryFeeMinor: 10000,
    hasDeal: true,
    heroImage: '/images/restaurants/com-ga-ba-sau-phu-nhuan-hero.jpg',
    menu: [
      {
        title: 'Mains',
        items: [
          {
            id: 'com-ga-ba-sau-phu-nhuan-com-ga-xoi-mo',
            name: 'Cơm gà xối mỡ',
            description: 'Crispy fried chicken, tomato rice, pickled cucumber.',
            amountMinor: 55000,
            image: '/images/dishes/com-ga-ba-sau-phu-nhuan-com-ga-xoi-mo.jpg',
          },
          {
            id: 'com-ga-ba-sau-phu-nhuan-com-ga-hai-nam',
            name: 'Cơm gà Hải Nam',
            description: 'Poached chicken, ginger rice, chili sauce.',
            amountMinor: 60000,
            image: '/images/dishes/com-ga-ba-sau-phu-nhuan-com-ga-hai-nam.jpg',
          },
          {
            id: 'com-ga-ba-sau-phu-nhuan-goi-ga-bap-cai',
            name: 'Gỏi gà bắp cải',
            description: 'Shredded chicken, cabbage, onion, Vietnamese coriander.',
            amountMinor: 50000,
            image: '/images/dishes/com-ga-ba-sau-phu-nhuan-goi-ga-bap-cai.jpg',
          },
          {
            id: 'com-ga-ba-sau-phu-nhuan-canh-bi-dao',
            name: 'Canh bí đao',
            description: 'Winter melon soup with chicken broth.',
            amountMinor: 20000,
            image: '/images/dishes/com-ga-ba-sau-phu-nhuan-canh-bi-dao.jpg',
          },
        ],
      },
      {
        title: 'Drinks',
        items: [
          {
            id: 'com-ga-ba-sau-phu-nhuan-tra-da',
            name: 'Trà đá',
            description: 'Iced jasmine green tea.',
            amountMinor: 15000,
            image: '/images/dishes/com-ga-ba-sau-phu-nhuan-tra-da.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'hai-san-kenh-te-quan-7',
    name: 'Hải Sản Kênh Tẻ Quận 7',
    city: 'hcmc',
    cuisineTag: 'Hải sản',
    rating: 4.5,
    reviewCount: 811,
    deliveryFeeMinor: 15000,
    hasDeal: false,
    heroImage: '/images/restaurants/hai-san-kenh-te-quan-7-hero.jpg',
    menu: [
      {
        title: 'Seafood',
        items: [
          {
            id: 'hai-san-kenh-te-quan-7-tom-nuong-muoi-ot',
            name: 'Tôm nướng muối ớt',
            description: 'Grilled tiger prawns, chili salt, lime.',
            amountMinor: 165000,
            image: '/images/dishes/hai-san-kenh-te-quan-7-tom-nuong-muoi-ot.jpg',
          },
          {
            id: 'hai-san-kenh-te-quan-7-muc-xao-sa-te',
            name: 'Mực xào sa tế',
            description: 'Wok-fried squid, satay chili, onion, celery.',
            amountMinor: 120000,
            image: '/images/dishes/hai-san-kenh-te-quan-7-muc-xao-sa-te.jpg',
          },
          {
            id: 'hai-san-kenh-te-quan-7-ngheu-hap-sa',
            name: 'Nghêu hấp sả',
            description: 'Steamed clams, lemongrass, chili, Thai basil.',
            amountMinor: 85000,
            image: '/images/dishes/hai-san-kenh-te-quan-7-ngheu-hap-sa.jpg',
          },
          {
            id: 'hai-san-kenh-te-quan-7-oc-len-xao-dua',
            name: 'Ốc len xào dừa',
            description: 'Mud creeper snails in coconut milk, rau răm.',
            amountMinor: 95000,
            image: '/images/dishes/hai-san-kenh-te-quan-7-oc-len-xao-dua.jpg',
          },
        ],
      },
      {
        title: 'Sides & drinks',
        items: [
          {
            id: 'hai-san-kenh-te-quan-7-com-chien-hai-san',
            name: 'Cơm chiên hải sản',
            description: 'Fried rice, shrimp, squid, egg, spring onion.',
            amountMinor: 75000,
            image: '/images/dishes/hai-san-kenh-te-quan-7-com-chien-hai-san.jpg',
          },
          {
            id: 'hai-san-kenh-te-quan-7-nuoc-dua-tuoi',
            name: 'Nước dừa tươi',
            description: 'Fresh young coconut, served chilled.',
            amountMinor: 30000,
            image: '/images/dishes/hai-san-kenh-te-quan-7-nuoc-dua-tuoi.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'banh-xeo-co-nam-tan-dinh',
    name: 'Bánh Xèo Cô Năm Tân Định',
    city: 'hcmc',
    cuisineTag: 'Bánh xèo',
    rating: 4.4,
    reviewCount: 347,
    deliveryFeeMinor: 0,
    hasDeal: false,
    heroImage: '/images/restaurants/banh-xeo-co-nam-tan-dinh-hero.jpg',
    menu: [
      {
        title: 'Pancakes',
        items: [
          {
            id: 'banh-xeo-co-nam-tan-dinh-banh-xeo-tom-thit',
            name: 'Bánh xèo tôm thịt',
            description: 'Crispy turmeric pancake, shrimp, pork, bean sprouts.',
            amountMinor: 65000,
            image: '/images/dishes/banh-xeo-co-nam-tan-dinh-banh-xeo-tom-thit.jpg',
          },
          {
            id: 'banh-xeo-co-nam-tan-dinh-banh-xeo-nam-chay',
            name: 'Bánh xèo nấm chay',
            description: 'Turmeric pancake, mixed mushrooms, tofu, bean sprouts.',
            amountMinor: 55000,
            image: '/images/dishes/banh-xeo-co-nam-tan-dinh-banh-xeo-nam-chay.jpg',
          },
          {
            id: 'banh-xeo-co-nam-tan-dinh-banh-khot',
            name: 'Bánh khọt',
            description: 'Mini coconut rice cakes, shrimp, scallion oil.',
            amountMinor: 60000,
            image: '/images/dishes/banh-xeo-co-nam-tan-dinh-banh-khot.jpg',
          },
        ],
      },
      {
        title: 'Drinks',
        items: [
          {
            id: 'banh-xeo-co-nam-tan-dinh-nuoc-mia-tac',
            name: 'Nước mía tắc',
            description: 'Pressed sugarcane juice with kumquat.',
            amountMinor: 20000,
            image: '/images/dishes/banh-xeo-co-nam-tan-dinh-nuoc-mia-tac.jpg',
          },
          {
            id: 'banh-xeo-co-nam-tan-dinh-tra-tac',
            name: 'Trà tắc',
            description: 'Iced tea, kumquat, a little honey.',
            amountMinor: 20000,
            image: '/images/dishes/banh-xeo-co-nam-tan-dinh-tra-tac.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'mi-quang-que-son-co-lien',
    name: 'Mì Quảng Quế Sơn Cô Liên',
    city: 'hcmc',
    cuisineTag: 'Mì Quảng',
    rating: 4.8,
    reviewCount: 2589,
    deliveryFeeMinor: 12000,
    hasDeal: true,
    heroImage: '/images/restaurants/mi-quang-que-son-co-lien-hero.jpg',
    menu: [
      {
        title: 'Noodles',
        items: [
          {
            id: 'mi-quang-que-son-co-lien-mi-quang-tom-thit',
            name: 'Mì Quảng tôm thịt',
            description: 'Turmeric noodles, shrimp, pork, peanuts, rice cracker.',
            amountMinor: 60000,
            image: '/images/dishes/mi-quang-que-son-co-lien-mi-quang-tom-thit.jpg',
          },
          {
            id: 'mi-quang-que-son-co-lien-mi-quang-ga',
            name: 'Mì Quảng gà',
            description: 'Turmeric noodles, braised chicken, quail egg, herbs.',
            amountMinor: 55000,
            image: '/images/dishes/mi-quang-que-son-co-lien-mi-quang-ga.jpg',
          },
          {
            id: 'mi-quang-que-son-co-lien-mi-quang-ca-loc',
            name: 'Mì Quảng cá lóc',
            description: 'Turmeric noodles, snakehead fish, peanuts, herbs.',
            amountMinor: 65000,
            image: '/images/dishes/mi-quang-que-son-co-lien-mi-quang-ca-loc.jpg',
          },
          {
            id: 'mi-quang-que-son-co-lien-banh-trang-me',
            name: 'Bánh tráng mè',
            description: 'Toasted sesame rice cracker, extra portion.',
            amountMinor: 10000,
            image: '/images/dishes/mi-quang-que-son-co-lien-banh-trang-me.jpg',
          },
        ],
      },
      {
        title: 'Drinks',
        items: [
          {
            id: 'mi-quang-que-son-co-lien-nuoc-sam',
            name: 'Nước sâm',
            description: 'Cooling herbal drink, monk fruit, sugarcane.',
            amountMinor: 15000,
            image: '/images/dishes/mi-quang-que-son-co-lien-nuoc-sam.jpg',
          },
        ],
      },
    ],
  },
  {
    slug: 'bo-bit-tet-chu-tam-go-vap',
    name: 'Bò Bít Tết Chú Tám Gò Vấp',
    city: 'hcmc',
    cuisineTag: 'Bò bít tết',
    rating: 4.3,
    reviewCount: 264,
    deliveryFeeMinor: 18000,
    hasDeal: false,
    heroImage: '/images/restaurants/bo-bit-tet-chu-tam-go-vap-hero.jpg',
    menu: [
      {
        title: 'Steaks',
        items: [
          {
            id: 'bo-bit-tet-chu-tam-go-vap-bo-bit-tet-op-la',
            name: 'Bò bít tết ốp la',
            description: 'Sizzling beef steak, fried egg, pâté, bread.',
            amountMinor: 95000,
            image: '/images/dishes/bo-bit-tet-chu-tam-go-vap-bo-bit-tet-op-la.jpg',
          },
          {
            id: 'bo-bit-tet-chu-tam-go-vap-bo-ne-thap-cam',
            name: 'Bò né thập cẩm',
            description: 'Beef, sausage, meatball, egg on sizzling pan.',
            amountMinor: 85000,
            image: '/images/dishes/bo-bit-tet-chu-tam-go-vap-bo-ne-thap-cam.jpg',
          },
          {
            id: 'bo-bit-tet-chu-tam-go-vap-than-bo-uc',
            name: 'Thăn bò Úc',
            description: 'Australian sirloin, pepper sauce, fries, salad.',
            amountMinor: 175000,
            image: '/images/dishes/bo-bit-tet-chu-tam-go-vap-than-bo-uc.jpg',
          },
        ],
      },
      {
        title: 'Sides & drinks',
        items: [
          {
            id: 'bo-bit-tet-chu-tam-go-vap-khoai-tay-chien',
            name: 'Khoai tây chiên',
            description: 'Crispy fries with chili and ketchup.',
            amountMinor: 35000,
            image: '/images/dishes/bo-bit-tet-chu-tam-go-vap-khoai-tay-chien.jpg',
          },
          {
            id: 'bo-bit-tet-chu-tam-go-vap-soda-chanh',
            name: 'Soda chanh',
            description: 'Lime soda, sugar syrup, crushed ice.',
            amountMinor: 25000,
            image: '/images/dishes/bo-bit-tet-chu-tam-go-vap-soda-chanh.jpg',
          },
        ],
      },
    ],
  },
];
