-- Events store: the six event migrations (ADR 0005 owner setup, step 2)
--
-- GENERATED by scripts/build-setup-sql.mjs from supabase/migrations/. Do not edit.
-- Paste the whole file into Supabase > SQL Editor > New query, and click Run once.
-- Everything runs in one transaction: if any statement fails, nothing is
-- applied, and the file can be run again after the problem is fixed.
-- The last result is a table of checks. Every row should say PASS.

begin;

-- ============================================================
-- 20260925000000_events.sql
-- ============================================================
-- ADR 0005 (docs/decisions/0005-hosted-event-store.md): one append-only
-- table, written directly by the browser with the publishable key. The
-- endpoint is public, so every bound in the ADR's "these bounds are part of
-- the decision" list is enforced here, in the database, not only by the
-- client code in src/lib/tracking-transport.ts — a request that never goes
-- through that code must still be refused.
--
-- Event names, per-event props shapes, and the variant/enum values below are
-- docs/measurement/66-parody-event-contract.md's contract (§3, §4), amended
-- by #67's order_placed handling_instructions/promo_code enums.
--
-- `anon` is created here, guarded, only so this migration is self-contained
-- and testable against a bare Postgres (supabase/migrations/events.test.ts) —
-- a real Supabase project already has it, and the guard makes re-running
-- this against one a no-op for that statement.
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin;
  end if;
end
$$;

create extension if not exists pgcrypto;

create schema if not exists private;

create table public.events (
  id uuid primary key,
  visitor_id uuid not null,
  session_id uuid not null,
  event_name text not null check (event_name in (
    'landing_viewed', 'restaurants_viewed', 'restaurant_opened',
    'cart_viewed', 'checkout_viewed', 'order_placed',
    'tracker_viewed', 'order_abandoned'
  )),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  -- ADR 0005 §1: "props jsonb checked to be an object of at most 1 KB".
  props jsonb not null check (
    jsonb_typeof(props) = 'object' and octet_length(props::text) <= 1024
  ),
  -- No experiment ships this round (event contract §3) — narrower than an
  -- open text column so nothing but null can land here until one does.
  variant text check (variant is null),
  constraint occurred_at_within_window check (
    occurred_at between received_at - interval '1 day' and received_at + interval '5 minutes'
  )
);

-- ADR 0005 §1: "anon gets a column-level insert grant and no select, update
-- or delete grant or policy, so rows are unreadable and unchangeable from
-- the outside."
revoke all on public.events from anon;
grant insert (id, visitor_id, session_id, event_name, occurred_at, props, variant)
  on public.events to anon;

alter table public.events enable row level security;
alter table public.events force row level security;

-- ADR 0005 §2 / event contract §4: each event name's props shape, encoded
-- so it can be the RLS insert policy's WITH CHECK below. `keys` sorted so
-- an exact-match array comparison also catches an extra, unlisted key.
create or replace function public.event_is_valid(event_name text, props jsonb)
returns boolean
language plpgsql
immutable
as $$
declare
  keys text[];
begin
  select coalesce(array_agg(k order by k), array[]::text[])
    into keys
  from jsonb_object_keys(props) k;

  if event_name = 'landing_viewed' then
    return keys = array['has_active_order']
      and jsonb_typeof(props->'has_active_order') = 'boolean';

  elsif event_name = 'restaurants_viewed' then
    return keys = array[]::text[];

  elsif event_name = 'restaurant_opened' then
    return keys = array['restaurant_slug']
      and jsonb_typeof(props->'restaurant_slug') = 'string'
      and length(props->>'restaurant_slug') between 1 and 60
      and props->>'restaurant_slug' ~ '^[a-z0-9]+(-[a-z0-9]+)*$';

  elsif event_name = 'cart_viewed' then
    return keys = array['item_count', 'subtotal_cents']
      and props->>'item_count' ~ '^[0-9]+$'
      and (props->>'item_count')::bigint between 0 and 999
      and props->>'subtotal_cents' ~ '^[0-9]+$'
      and (props->>'subtotal_cents')::bigint between 0 and 100000;

  elsif event_name = 'checkout_viewed' then
    return keys = array['item_count', 'subtotal_cents']
      and props->>'item_count' ~ '^[0-9]+$'
      and (props->>'item_count')::bigint between 1 and 999
      and props->>'subtotal_cents' ~ '^[0-9]+$'
      and (props->>'subtotal_cents')::bigint between 1 and 100000;

  elsif event_name = 'order_placed' then
    return keys = array[
        'drop_off_spot', 'handling_instructions', 'item_count', 'order_id',
        'promo_code', 'subtotal_cents', 'tip_percent', 'utensils'
      ]
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and props->>'item_count' ~ '^[0-9]+$'
      and (props->>'item_count')::bigint between 1 and 999
      and props->>'subtotal_cents' ~ '^[0-9]+$'
      and (props->>'subtotal_cents')::bigint between 1 and 100000
      and props->>'drop_off_spot' in ('couch', 'wherever_i_am', 'the_void', 'behind_you')
      -- #67's amended contract (issue #68 AC6, moved from #67 AC8(c)):
      and props->>'handling_instructions' in ('guard_it', 'wing_it', 'two_hands', 'surprise_me')
      and jsonb_typeof(props->'utensils') = 'boolean'
      and props->>'tip_percent' ~ '^[0-9]+$'
      and (props->>'tip_percent')::int in (0, 10, 15, 20)
      and props->>'promo_code' in ('dont_drop10', 'still_here', 'clumsy15', 'gotcha');

  elsif event_name = 'tracker_viewed' then
    return keys = array['minutes_since_order', 'order_id', 'view_number']
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and jsonb_typeof(props->'minutes_since_order') = 'number'
      and (props->>'minutes_since_order')::numeric >= 0
      and props->>'view_number' ~ '^[0-9]+$'
      and (props->>'view_number')::bigint >= 1;

  elsif event_name = 'order_abandoned' then
    return keys = array['minutes_since_order', 'order_id', 'view_count']
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and jsonb_typeof(props->'minutes_since_order') = 'number'
      and (props->>'minutes_since_order')::numeric >= 0
      and props->>'view_count' ~ '^[0-9]+$'
      and (props->>'view_count')::bigint >= 1;

  else
    return false;
  end if;
end;
$$;

-- ADR 0005 §2: "the RLS insert policy for anon is
-- with check (public.event_is_valid(event_name, props))".
create policy events_insert_anon on public.events
  for insert
  to anon
  with check (public.event_is_valid(event_name, props));

-- ADR 0005 §4: "60 writes per IP per 5 minutes, keyed on a salted hash of
-- the IP in a non-exposed schema, purged after one hour. No IP reaches
-- events" directly — refused before the row is written, by this trigger.
-- Reads the IP from the `request.headers` GUC PostgREST sets on every
-- request (a JSON object of the incoming headers — a GUC name cannot
-- itself contain the hyphens an HTTP header name does, so PostgREST packs
-- all of them into this one JSON-valued setting rather than one GUC per
-- header). A session with no such header (this migration applied by hand,
-- or a test that never sets it) is not rate-limited, since there is no IP
-- to key on.
create table private.write_log (
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create index write_log_ip_hash_created_at_idx on private.write_log (ip_hash, created_at);

-- Salts the IP hash below. Generated once, here, at migration time, so the
-- hash is never unsalted by default — nothing has to remember to configure
-- it. Lives in `private`, which `anon` has no grant on at all, and is read
-- only by the SECURITY DEFINER function below, so nobody who can reach the
-- Data API can read it back out.
create table private.rate_limit_salt (
  id boolean primary key default true,
  salt bytea not null,
  constraint rate_limit_salt_single_row check (id)
);

insert into private.rate_limit_salt (salt) values (gen_random_bytes(32));

-- security definer: anon has no grant on the private schema at all (the
-- point of putting write_log there), so this must run as the function's
-- owner rather than the inserting role. search_path is pinned so a
-- same-named object earlier on some other role's path can't hijack it.
create or replace function public.enforce_write_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  headers jsonb;
  xff text;
  xff_parts text[];
  client_ip text;
  v_salt bytea;
  v_ip_hash text;
  recent_count int;
begin
  headers := nullif(current_setting('request.headers', true), '')::jsonb;

  -- Prefer a header the client cannot set. `cf-connecting-ip` is set by
  -- Supabase's edge (fronted by Cloudflare), overwriting any value the
  -- client sends. Where it's absent, fall back to the rightmost
  -- `x-forwarded-for` entry — the one the nearest trusted proxy appends —
  -- rather than the leftmost, which is whatever the client sends and can be
  -- rotated on every request to defeat this limit entirely: driver review
  -- on #68 reproduced 200 of 200 spoofed-leftmost inserts accepted against
  -- this 60-per-5-minute limit. Which header the live project actually
  -- supplies is an assumption to confirm on the first real deploy — see
  -- the pull request body.
  client_ip := nullif(headers ->> 'cf-connecting-ip', '');

  if client_ip is null then
    xff := nullif(headers ->> 'x-forwarded-for', '');
    if xff is not null then
      xff_parts := string_to_array(xff, ',');
      client_ip := nullif(trim(both ' ' from xff_parts[array_length(xff_parts, 1)]), '');
    end if;
  end if;

  if client_ip is not null then
    select salt into v_salt from private.rate_limit_salt;

    v_ip_hash := encode(digest(client_ip::bytea || v_salt, 'sha256'), 'hex');

    delete from private.write_log where created_at < now() - interval '1 hour';

    select count(*) into recent_count
    from private.write_log
    where ip_hash = v_ip_hash and created_at > now() - interval '5 minutes';

    if recent_count >= 60 then
      raise exception 'rate limit exceeded' using errcode = 'P0001';
    end if;

    insert into private.write_log (ip_hash) values (v_ip_hash);
  end if;

  return new;
end;
$$;

create trigger events_rate_limit
  before insert on public.events
  for each row
  execute function public.enforce_write_rate_limit();

-- ADR 0005 §5 / docs/measurement/66-parody-event-contract.md §5-§6: "every
-- metric is computed from `events_clean`, never raw `events`". A
-- pass-through view for now — deciding which sequences or rates count as
-- "humanly impossible" is a measurement judgment for the analyst's
-- follow-up, not this migration's to invent (driver review on #68). The
-- raw `events` table stays whole either way; this view is the seam where
-- exclusion rules land later without any query above it changing.
--
-- `security_invoker = true` so the view runs with the querying role's own
-- rights, not the view owner's — a default (invoker off) view over a single
-- table is auto-updatable and runs as the owner, which would let anyone who
-- can reach it bypass `events`' RLS and grants entirely. Supabase also grants
-- `anon` (and `authenticated`) default privileges on every new relation in
-- `public`, so the view is unreadable/unwritable from the outside only once
-- those grants are explicitly revoked below too (driver review round 2 on
-- #68: an unguarded pass-through view let anon select, update, and delete
-- every row through this view despite `events` itself being locked down).
create view public.events_clean
  with (security_invoker = true) as
  select * from public.events;

revoke all on public.events_clean from anon;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on public.events_clean from authenticated';
  end if;
end
$$;

-- ============================================================
-- 20260926000000_two_city_event_contract.sql
-- ============================================================
-- #85: additive migration for the revised event contract
-- (docs/measurement/81-two-city-event-contract.md), amending ADR 0005 per
-- ADR 0007 (docs/decisions/0007-two-city-event-contract.md). Strictly
-- additive per house rules and the contract's own "AC7": this file only
-- ALTERs what 20260925000000_events.sql created and replaces
-- `event_is_valid`; that file itself is untouched.
--
-- `event_name`'s CHECK is replaced, not widened: the old parody-only names
-- (`landing_viewed`, `restaurants_viewed`, `order_abandoned`) are retired
-- outright (contract §1, §6) and must no longer validate a *new* insert.
-- Dropping and re-adding that CHECK is what makes an old name fail again,
-- but a plain `add constraint` would also validate it against every row
-- already in the table — on a live project that has been running #66's
-- funnel, that would fail the migration outright on its own historical
-- data. `not valid` skips that backfill scan while still enforcing the
-- new list on every row inserted from here on (Postgres: a `not valid`
-- check "will still be enforced against subsequent inserts or updates"),
-- which is exactly the contract's "existing historical rows already in
-- events are untouched either way" (§"AC7").
alter table public.events
  drop constraint events_event_name_check;

alter table public.events
  add constraint events_event_name_check check (event_name in (
    'location_selected', 'home_viewed', 'restaurant_opened', 'cart_viewed',
    'checkout_viewed', 'flash_sheet_shown', 'flash_sheet_closed',
    'order_placed', 'tracker_viewed', 'order_delivered', 'rating_submitted'
  )) not valid;

-- Contract §2: one shared per-currency bound, reused by every
-- `amount_minor` prop below except `flash_sheet_shown`'s, which is bounded
-- to a narrower, fixed drawn range instead (§7) — pulled out once rather
-- than repeated across cart/checkout/order's subtotal and saved amount,
-- since it's the same range check every time.
create or replace function public.amount_minor_in_bounds(
  props jsonb, field text, currency text, allow_zero boolean
)
returns boolean
language plpgsql
immutable
as $$
declare
  raw text;
  hi bigint;
  lo bigint;
begin
  raw := props ->> field;
  if raw is null or raw !~ '^[0-9]+$' then
    return false;
  end if;
  if currency = 'USD' then
    hi := 100000;
  elsif currency = 'VND' then
    hi := 5000000;
  else
    return false;
  end if;
  lo := case when allow_zero then 0 else 1 end;
  return raw::bigint between lo and hi;
end;
$$;

-- Event contract #81 §7: every accepted event name and its props shape,
-- replacing #66's version (docs/measurement/66-parody-event-contract.md,
-- now superseded in full). Retired names simply aren't listed below, so
-- they fall through to the `else return false` branch, same as any other
-- unrecognised name.
create or replace function public.event_is_valid(event_name text, props jsonb)
returns boolean
language plpgsql
immutable
as $$
declare
  keys text[];
begin
  select coalesce(array_agg(k order by k), array[]::text[])
    into keys
  from jsonb_object_keys(props) k;

  if event_name = 'location_selected' then
    return keys = array['city', 'is_switch']
      and props->>'city' in ('sf', 'hcmc')
      and jsonb_typeof(props->'is_switch') = 'boolean';

  elsif event_name = 'home_viewed' then
    return keys = array['city']
      and props->>'city' in ('sf', 'hcmc');

  elsif event_name = 'restaurant_opened' then
    return keys = array['city', 'restaurant_slug']
      and props->>'city' in ('sf', 'hcmc')
      and jsonb_typeof(props->'restaurant_slug') = 'string'
      and length(props->>'restaurant_slug') between 1 and 60
      and props->>'restaurant_slug' ~ '^[a-z0-9]+(-[a-z0-9]+)*$';

  elsif event_name = 'cart_viewed' then
    return keys = array['amount_minor', 'currency', 'item_count']
      and props->>'currency' in ('USD', 'VND')
      and props->>'item_count' ~ '^[0-9]+$'
      and (props->>'item_count')::bigint between 0 and 999
      and public.amount_minor_in_bounds(props, 'amount_minor', props->>'currency', true);

  elsif event_name = 'checkout_viewed' then
    return keys = array['amount_minor', 'currency', 'item_count']
      and props->>'currency' in ('USD', 'VND')
      and props->>'item_count' ~ '^[0-9]+$'
      and (props->>'item_count')::bigint between 1 and 999
      and public.amount_minor_in_bounds(props, 'amount_minor', props->>'currency', false);

  elsif event_name = 'flash_sheet_shown' then
    return keys = array['amount_minor', 'city', 'currency', 'restaurant_slugs']
      and props->>'city' in ('sf', 'hcmc')
      and props->>'currency' in ('USD', 'VND')
      and props->>'amount_minor' ~ '^[0-9]+$'
      and (
        (props->>'currency' = 'VND' and (props->>'amount_minor')::bigint between 10000 and 30000)
        or
        (props->>'currency' = 'USD' and (props->>'amount_minor')::bigint between 200 and 600)
      )
      and jsonb_typeof(props->'restaurant_slugs') = 'array'
      and jsonb_array_length(props->'restaurant_slugs') = 2
      and (
        select bool_and(
          jsonb_typeof(elem) = 'string'
          and length(elem #>> '{}') between 1 and 60
          and (elem #>> '{}') ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
        )
        from jsonb_array_elements(props->'restaurant_slugs') elem
      );

  elsif event_name = 'flash_sheet_closed' then
    return keys = array['city', 'outcome', 'restaurant_slug', 'seconds_remaining']
      and props->>'city' in ('sf', 'hcmc')
      and props->>'outcome' in ('restaurant_tapped', 'dismissed', 'expired')
      and props->>'seconds_remaining' ~ '^[0-9]+$'
      and (props->>'seconds_remaining')::int between 0 and 900
      and (
        (props->>'outcome' = 'restaurant_tapped'
          and jsonb_typeof(props->'restaurant_slug') = 'string'
          and props->>'restaurant_slug' <> 'none'
          and length(props->>'restaurant_slug') between 1 and 60
          and props->>'restaurant_slug' ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
        or
        (props->>'outcome' <> 'restaurant_tapped' and props->>'restaurant_slug' = 'none')
      );

  elsif event_name = 'order_placed' then
    return keys = array[
        'amount_minor', 'applied_voucher_ids', 'currency', 'delivery_instructions',
        'drop_off_preset', 'item_count', 'order_id', 'saved_amount_minor', 'utensils'
      ]
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and props->>'item_count' ~ '^[0-9]+$'
      and (props->>'item_count')::bigint between 1 and 999
      and props->>'currency' in ('USD', 'VND')
      and public.amount_minor_in_bounds(props, 'amount_minor', props->>'currency', false)
      and public.amount_minor_in_bounds(props, 'saved_amount_minor', props->>'currency', true)
      and props->>'drop_off_preset' in ('home', 'office', 'front_desk')
      and props->>'delivery_instructions' in ('leave_at_door', 'hand_to_me', 'meet_downstairs', 'call_on_arrival')
      and jsonb_typeof(props->'utensils') = 'boolean'
      and jsonb_typeof(props->'applied_voucher_ids') = 'array'
      and jsonb_array_length(props->'applied_voucher_ids') between 0 and 2
      and (
        select coalesce(bool_and(
          v is not null and v in (
            'hcmc-delivery-entry', 'hcmc-discount-t1', 'hcmc-discount-t2', 'hcmc-discount-t3', 'hcmc-flash',
            'sf-delivery-entry', 'sf-discount-t1', 'sf-discount-t2', 'sf-discount-t3', 'sf-flash'
          )
        ), true)
        from jsonb_array_elements_text(props->'applied_voucher_ids') v
      )
      and (
        select count(distinct v) from jsonb_array_elements_text(props->'applied_voucher_ids') v
      ) = jsonb_array_length(props->'applied_voucher_ids');
      -- Contract §7's cross-field invariant on this row — "saved_amount_minor
      -- is 0 iff applied_voucher_ids is []" — is deliberately NOT enforced
      -- here. Decided on #79 (2026-09-26 11:47): a CHECK here would turn a
      -- client arithmetic bug into an order_placed row the store silently
      -- drops, on the primary metric's numerator. An inconsistent row that
      -- lands can be counted and excluded later; a refused one is gone. The
      -- invariant is #89's to enforce client-side. See ADR 0007.

  elsif event_name = 'tracker_viewed' then
    return keys = array['minutes_since_order', 'order_id', 'view_number']
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and jsonb_typeof(props->'minutes_since_order') = 'number'
      and (props->>'minutes_since_order')::numeric >= 0
      and props->>'view_number' ~ '^[0-9]+$'
      and (props->>'view_number')::bigint >= 1;

  elsif event_name = 'order_delivered' then
    return keys = array['minutes_since_order', 'order_id']
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and jsonb_typeof(props->'minutes_since_order') = 'number'
      and (props->>'minutes_since_order')::numeric >= 0;

  elsif event_name = 'rating_submitted' then
    return keys = array['order_id', 'stars', 'tags']
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and props->>'stars' ~ '^[0-9]+$'
      and (props->>'stars')::int between 1 and 5
      and jsonb_typeof(props->'tags') = 'array'
      and jsonb_array_length(props->'tags') between 0 and 3
      and (
        select coalesce(bool_and(
          t is not null and t in ('fast', 'great_packaging', 'order_was_correct')
        ), true)
        from jsonb_array_elements_text(props->'tags') t
      )
      and (
        select count(distinct t) from jsonb_array_elements_text(props->'tags') t
      ) = jsonb_array_length(props->'tags');

  else
    return false;
  end if;
end;
$$;

-- ============================================================
-- 20260930000000_rate_limit_search_path.sql
-- ============================================================
-- #222: additive migration fixing the rate-limit trigger's search_path for
-- Supabase's real schema layout — ADR 0005
-- (docs/decisions/0005-hosted-event-store.md). Strictly additive per house
-- rules: 20260925000000_events.sql (and every other file in this directory)
-- is untouched; this file only ALTERs the function it created.
--
-- On Supabase, pgcrypto is installed into an `extensions` schema, not
-- `public` — the platform's own default, not a project setting — and the
-- platform's own default `search_path` (`"$user", public, extensions`) is
-- what makes `digest()`/`gen_random_bytes()` resolve ambiently everywhere.
-- `public.enforce_write_rate_limit()` is `security definer set search_path =
-- public, private, pg_temp`, deliberately pinned (that migration's own
-- comment) so a same-named object earlier on some other role's path can't
-- hijack it — but a pinned search_path ignores the session/platform default
-- entirely, and this pin never listed `extensions`. Every insert as `anon`
-- fires this trigger, which calls `digest()` to hash the rate-limit key, and
-- on Supabase's real layout that call fails with "function digest(bytea,
-- unknown) does not exist" — silently, since the browser swallows the error
-- (ADR 0005), so the store looks fine and records nothing. Reproduced in
-- rate-limit-search-path.migration.test.ts (AC1), watched failing before
-- this file existed — see that test and the pull request for the exact
-- failure — and passing once this file is applied (AC2).
--
-- Adding `extensions` to the pinned list keeps the same protection this
-- search_path was written for (no unpinned schema, no `$user`) while
-- resolving `digest()` on both layouts: the top-level PGlite layout every
-- other test in this directory uses (pgcrypto in `public`) still finds it
-- through `public`, unaffected by `extensions` also being on the path
-- (rate-limit-search-path.migration.test.ts, AC3).
alter function public.enforce_write_rate_limit()
  set search_path = public, private, extensions, pg_temp;

-- ============================================================
-- 20261001000000_analytics_readiness_event_contract.sql
-- ============================================================
-- #224: additive migration for the analytics-readiness event contract
-- (docs/measurement/219-analytics-readiness-contract.md, §13 items 1-6),
-- amending ADR 0005 and ADR 0007 per
-- docs/decisions/0012-analytics-readiness-event-shapes.md. Strictly
-- additive: this file replaces `event_is_valid` and the `event_name` CHECK
-- only; no applied migration is edited and no stored row is changed.
--
-- `session_started`, the `is_internal` column and `events_clean` are #225's
-- (§13 item 7), so `session_started` is not in the name list below yet.
--
-- STRICT SUPERSET (contract §13, amendment 4): every (event_name, props)
-- pair the previous `event_is_valid` (20260926000000_two_city_event_contract.sql)
-- accepts is still accepted here. Tabs that are already open keep sending
-- #81's shapes, and a refused row is lost silently (ADR 0005). This
-- deliberately reverses #81's "old shapes rejected" posture (its AC7).
-- Cross-field invariants (currency against city, saved amount against
-- vouchers, ...) are still NOT checked in the store; ADR 0007 keeps them in
-- client tests.

-- Dropped and re-added `not valid`, as in #85, so historical rows aren't
-- re-scanned. The 11 names #81 kept, plus the six new events.
alter table public.events
  drop constraint events_event_name_check;

alter table public.events
  add constraint events_event_name_check check (event_name in (
    'location_selected', 'home_viewed', 'restaurant_opened', 'cart_viewed',
    'checkout_viewed', 'flash_sheet_shown', 'flash_sheet_closed',
    'order_placed', 'tracker_viewed', 'order_delivered', 'rating_submitted',
    'driver_rating_submitted', 'tip_sent', 'sign_in_prompt_shown',
    'sign_in_started', 'sign_in_completed', 'wallet_short_shown'
  )) not valid;

create or replace function public.event_is_valid(event_name text, props jsonb)
returns boolean
language plpgsql
immutable
as $$
declare
  keys text[];
begin
  select coalesce(array_agg(k order by k), array[]::text[])
    into keys
  from jsonb_object_keys(props) k;

  if event_name = 'location_selected' then
    return keys = array['city', 'is_switch']
      and props->>'city' in ('sf', 'hcmc', 'la')
      and jsonb_typeof(props->'is_switch') = 'boolean';

  elsif event_name = 'home_viewed' then
    return keys = array['city']
      and props->>'city' in ('sf', 'hcmc', 'la');

  elsif event_name = 'restaurant_opened' then
    return keys = array['city', 'restaurant_slug']
      and props->>'city' in ('sf', 'hcmc', 'la')
      and jsonb_typeof(props->'restaurant_slug') = 'string'
      and length(props->>'restaurant_slug') between 1 and 60
      and props->>'restaurant_slug' ~ '^[a-z0-9]+(-[a-z0-9]+)*$';

  elsif event_name = 'cart_viewed' then
    -- #81's 3-key shape, or the 4-key shape with city.
    return (
        keys = array['amount_minor', 'currency', 'item_count']
        or (keys = array['amount_minor', 'city', 'currency', 'item_count']
            and props->>'city' in ('sf', 'hcmc', 'la'))
      )
      and props->>'currency' in ('USD', 'VND')
      and props->>'item_count' ~ '^[0-9]+$'
      and (props->>'item_count')::bigint between 0 and 999
      and public.amount_minor_in_bounds(props, 'amount_minor', props->>'currency', true);

  elsif event_name = 'checkout_viewed' then
    return (
        keys = array['amount_minor', 'currency', 'item_count']
        or (keys = array['amount_minor', 'city', 'currency', 'item_count']
            and props->>'city' in ('sf', 'hcmc', 'la'))
      )
      and props->>'currency' in ('USD', 'VND')
      and props->>'item_count' ~ '^[0-9]+$'
      and (props->>'item_count')::bigint between 1 and 999
      and public.amount_minor_in_bounds(props, 'amount_minor', props->>'currency', false);

  elsif event_name = 'flash_sheet_shown' then
    -- 5-6 distinct slugs (the product's real draw), or 2 as #81 accepted
    -- (kept only for the strict superset; no current client sends 2).
    return keys = array['amount_minor', 'city', 'currency', 'restaurant_slugs']
      and props->>'city' in ('sf', 'hcmc', 'la')
      and props->>'currency' in ('USD', 'VND')
      and props->>'amount_minor' ~ '^[0-9]+$'
      and (
        (props->>'currency' = 'VND' and (props->>'amount_minor')::bigint between 10000 and 30000)
        or
        (props->>'currency' = 'USD' and (props->>'amount_minor')::bigint between 200 and 600)
      )
      and jsonb_typeof(props->'restaurant_slugs') = 'array'
      and jsonb_array_length(props->'restaurant_slugs') in (2, 5, 6)
      and (
        select bool_and(
          jsonb_typeof(elem) = 'string'
          and length(elem #>> '{}') between 1 and 60
          and (elem #>> '{}') ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
        )
        from jsonb_array_elements(props->'restaurant_slugs') elem
      )
      and (
        jsonb_array_length(props->'restaurant_slugs') = 2
        or (
          select count(distinct elem #>> '{}') from jsonb_array_elements(props->'restaurant_slugs') elem
        ) = jsonb_array_length(props->'restaurant_slugs')
      );

  elsif event_name = 'flash_sheet_closed' then
    return keys = array['city', 'outcome', 'restaurant_slug', 'seconds_remaining']
      and props->>'city' in ('sf', 'hcmc', 'la')
      and props->>'outcome' in ('restaurant_tapped', 'dismissed', 'expired')
      and props->>'seconds_remaining' ~ '^[0-9]+$'
      and (props->>'seconds_remaining')::int between 0 and 900
      and (
        (props->>'outcome' = 'restaurant_tapped'
          and jsonb_typeof(props->'restaurant_slug') = 'string'
          and props->>'restaurant_slug' <> 'none'
          and length(props->>'restaurant_slug') between 1 and 60
          and props->>'restaurant_slug' ~ '^[a-z0-9]+(-[a-z0-9]+)*$')
        or
        (props->>'outcome' <> 'restaurant_tapped' and props->>'restaurant_slug' = 'none')
      );

  elsif event_name = 'order_placed' then
    -- #81's 9-key shape, or the 14-key shape (contract §8). The nine shared
    -- fields are checked the same way for both; the five new ones only when
    -- present. Cross-field invariants are not enforced (ADR 0007).
    return (
        keys = array[
          'amount_minor', 'applied_voucher_ids', 'currency', 'delivery_instructions',
          'drop_off_preset', 'item_count', 'order_id', 'saved_amount_minor', 'utensils'
        ]
        or (
          keys = array[
            'amount_minor', 'applied_voucher_ids', 'city', 'currency', 'delivery_instructions',
            'drop_off_preset', 'item_count', 'order_id', 'saved_amount_minor',
            'thanks_voucher_amount_minor', 'utensils', 'vip_level', 'vip_saved_amount_minor',
            'wallet_paid'
          ]
          and props->>'city' in ('sf', 'hcmc', 'la')
          and props->>'vip_level' in ('none', 'gold', 'platinum')
          and jsonb_typeof(props->'wallet_paid') = 'boolean'
          and public.amount_minor_in_bounds(props, 'thanks_voucher_amount_minor', props->>'currency', true)
          and public.amount_minor_in_bounds(props, 'vip_saved_amount_minor', props->>'currency', true)
        )
      )
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and props->>'item_count' ~ '^[0-9]+$'
      and (props->>'item_count')::bigint between 1 and 999
      and props->>'currency' in ('USD', 'VND')
      and public.amount_minor_in_bounds(props, 'amount_minor', props->>'currency', false)
      and public.amount_minor_in_bounds(props, 'saved_amount_minor', props->>'currency', true)
      and props->>'drop_off_preset' in ('home', 'office', 'front_desk')
      and props->>'delivery_instructions' in ('leave_at_door', 'hand_to_me', 'meet_downstairs', 'call_on_arrival')
      and jsonb_typeof(props->'utensils') = 'boolean'
      and jsonb_typeof(props->'applied_voucher_ids') = 'array'
      and jsonb_array_length(props->'applied_voucher_ids') between 0 and 2
      and (
        select coalesce(bool_and(
          v is not null and v in (
            'hcmc-delivery-entry', 'hcmc-discount-t1', 'hcmc-discount-t2', 'hcmc-discount-t3', 'hcmc-flash',
            'sf-delivery-entry', 'sf-discount-t1', 'sf-discount-t2', 'sf-discount-t3', 'sf-flash',
            'la-delivery-entry', 'la-discount-t1', 'la-discount-t2', 'la-discount-t3', 'la-flash'
          )
        ), true)
        from jsonb_array_elements_text(props->'applied_voucher_ids') v
      )
      and (
        select count(distinct v) from jsonb_array_elements_text(props->'applied_voucher_ids') v
      ) = jsonb_array_length(props->'applied_voucher_ids');

  elsif event_name = 'tracker_viewed' then
    return keys = array['minutes_since_order', 'order_id', 'view_number']
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and jsonb_typeof(props->'minutes_since_order') = 'number'
      and (props->>'minutes_since_order')::numeric >= 0
      and props->>'view_number' ~ '^[0-9]+$'
      and (props->>'view_number')::bigint >= 1;

  elsif event_name = 'order_delivered' then
    return keys = array['minutes_since_order', 'order_id']
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and jsonb_typeof(props->'minutes_since_order') = 'number'
      and (props->>'minutes_since_order')::numeric >= 0;

  elsif event_name = 'rating_submitted' then
    return keys = array['order_id', 'stars', 'tags']
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and props->>'stars' ~ '^[0-9]+$'
      and (props->>'stars')::int between 1 and 5
      and jsonb_typeof(props->'tags') = 'array'
      and jsonb_array_length(props->'tags') between 0 and 3
      and (
        select coalesce(bool_and(
          t is not null and t in ('fast', 'great_packaging', 'order_was_correct')
        ), true)
        from jsonb_array_elements_text(props->'tags') t
      )
      and (
        select count(distinct t) from jsonb_array_elements_text(props->'tags') t
      ) = jsonb_array_length(props->'tags');

  -- The six new events (contract §8). Each is wrapped in coalesce so a
  -- missing or mistyped value refuses the row rather than yielding null,
  -- which a CHECK would let through.
  elsif event_name = 'driver_rating_submitted' then
    return coalesce(
      keys = array['order_id', 'stars']
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and props->>'stars' ~ '^[0-9]+$'
      and (props->>'stars')::int between 1 and 5,
      false);

  elsif event_name = 'tip_sent' then
    return coalesce(
      keys = array['currency', 'order_id', 'tip_amount_minor']
      and props->>'order_id' ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      and jsonb_typeof(props->'tip_amount_minor') = 'number'
      and (
        (props->>'currency' = 'USD' and props->>'tip_amount_minor' in ('100', '200', '300'))
        or
        (props->>'currency' = 'VND' and props->>'tip_amount_minor' in ('10000', '20000', '30000'))
      ),
      false);

  elsif event_name = 'sign_in_prompt_shown' then
    return coalesce(
      keys = array['surface']
      and props->>'surface' in ('checkout', 'tip'),
      false);

  elsif event_name = 'sign_in_started' then
    return coalesce(
      keys = array['provider', 'surface']
      and props->>'provider' in ('google', 'apple')
      and props->>'surface' in ('checkout', 'tip'),
      false);

  elsif event_name = 'sign_in_completed' then
    return coalesce(
      keys = array['outcome', 'provider', 'surface']
      and props->>'outcome' in ('success', 'failed')
      and props->>'provider' in ('google', 'apple')
      and props->>'surface' in ('checkout', 'tip'),
      false);

  elsif event_name = 'wallet_short_shown' then
    return coalesce(
      keys = array['city', 'surface']
      and props->>'city' in ('sf', 'hcmc', 'la')
      and props->>'surface' in ('checkout', 'tip'),
      false);

  else
    return false;
  end if;
end;
$$;

-- ============================================================
-- 20261002000000_session_started_and_is_internal.sql
-- ============================================================
-- #225: acquisition and owner traffic
-- (docs/measurement/219-analytics-readiness-contract.md §5, §6 and §13
-- item 7), amending ADR 0005 and ADR 0007 per
-- docs/decisions/0013-session-started-and-is-internal.md. Additive: no
-- applied migration is edited and no stored row is changed. This file
--   1. adds the `session_started` event (name CHECK and a validator branch),
--   2. adds the `is_internal` column and anon's insert grant on it, and
--   3. recreates `events_clean` so it excludes every row of a visitor who
--      has any `is_internal = true` row.
--
-- STRICT SUPERSET (contract §13, amendment 4): #224's validator is kept
-- whole under a new name, `event_is_valid_224`, and the new
-- `event_is_valid` decides `session_started` itself and hands every other
-- event name to it unchanged. So every (event_name, props) pair the store
-- accepts on main is still accepted, by the very same code.

-- 1a. Event names: #224's 17 plus `session_started`. Dropped and re-added
-- `not valid`, as in #85 and #224, so historical rows aren't re-scanned.
alter table public.events
  drop constraint events_event_name_check;

alter table public.events
  add constraint events_event_name_check check (event_name in (
    'location_selected', 'home_viewed', 'restaurant_opened', 'cart_viewed',
    'checkout_viewed', 'flash_sheet_shown', 'flash_sheet_closed',
    'order_placed', 'tracker_viewed', 'order_delivered', 'rating_submitted',
    'driver_rating_submitted', 'tip_sent', 'sign_in_prompt_shown',
    'sign_in_started', 'sign_in_completed', 'wallet_short_shown',
    'session_started'
  )) not valid;

-- 1b. Keep #224's validator, unchanged, under its own name. Renaming keeps
-- its body, owner and grants. Its execute grant is deliberately left as it
-- is: the RLS check below runs as the inserting role, so `anon` must still
-- be able to execute it through the wrapper.
alter function public.event_is_valid(text, jsonb) rename to event_is_valid_224;

-- The wrapper. `session_started` carries acquisition and nothing else
-- (contract §6): the referring host, or one of the three sentinels, and the
-- three utm_ values, each a sentinel or a value matching the pattern. `/`,
-- `?`, `@`, `:`, `=` and `&` cannot match either pattern, so no URL, query
-- string or email address can be stored in these props. Wrapped in
-- coalesce so a missing or mistyped value refuses the row rather than
-- yielding null, which a policy check would let through.
create function public.event_is_valid(event_name text, props jsonb)
returns boolean
language plpgsql
immutable
as $$
declare
  keys text[];
  utm_key text;
begin
  if event_name = 'session_started' then
    select coalesce(array_agg(k order by k), array[]::text[])
      into keys
    from jsonb_object_keys(props) k;

    if not coalesce(
      keys = array['referrer_host', 'utm_campaign', 'utm_medium', 'utm_source']
      and jsonb_typeof(props->'referrer_host') = 'string'
      and (
        props->>'referrer_host' in ('(none)', '(self)', '(invalid)')
        or (
          length(props->>'referrer_host') between 1 and 253
          and props->>'referrer_host' ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)*$'
        )
      ),
      false) then
      return false;
    end if;

    foreach utm_key in array array['utm_source', 'utm_medium', 'utm_campaign'] loop
      if not coalesce(
        jsonb_typeof(props->utm_key) = 'string'
        and (
          props->>utm_key in ('(none)', '(invalid)')
          or props->>utm_key ~ '^[a-z0-9][a-z0-9._-]{0,49}$'
        ),
        false) then
        return false;
      end if;
    end loop;

    return true;
  end if;

  return public.event_is_valid_224(event_name, props);
end;
$$;

-- The policy was bound to the function itself, not its name, so after the
-- rename it calls `event_is_valid_224`. Recreate it against the wrapper,
-- with the same name, role and check expression ADR 0005 §2 records.
drop policy events_insert_anon on public.events;

create policy events_insert_anon on public.events
  for insert
  to anon
  with check (public.event_is_valid(event_name, props));

-- 2. The owner-traffic flag (contract §5, O12). A column, not a prop, so it
-- rides on every event without changing any event's key set. The default
-- lets a tab still running the previous client insert without it. True or
-- false only: never an identifier, never linked to sign-in.
alter table public.events
  add column is_internal boolean not null default false;

grant insert (is_internal) on public.events to anon;

-- 3. `events_clean`'s first real exclusion rule (contract §5): drop every
-- row whose visitor has at least one flagged row, so the owner's earlier,
-- unflagged rows from the same browser go too. Recreated rather than
-- replaced, because a `select *` view does not pick up a new column; the
-- same `security_invoker` setting and the same revokes as
-- 20260925000000_events.sql, since Supabase grants anon and authenticated
-- default privileges on every new relation in `public`.
drop view public.events_clean;

create view public.events_clean
  with (security_invoker = true) as
  select e.*
  from public.events e
  where not exists (
    select 1
    from public.events flagged
    where flagged.visitor_id = e.visitor_id
      and flagged.is_internal
  );

revoke all on public.events_clean from anon;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on public.events_clean from authenticated';
  end if;
end
$$;

-- ============================================================
-- 20261003000000_second_pass_readiness.sql
-- ============================================================
-- #273: additive migration for the second-pass measurement contract
-- (docs/measurement/270-analytics-readiness-second-pass.md §4.4, §5.1 and
-- §11), amending ADR 0005 and ADR 0007 per ADRs 0014, 0015 and 0016.
-- Additive: no applied migration is edited and no stored row is changed.
-- This file
--   1. accepts two new event shapes (order_placed's 15-key shape and
--      flash_sheet_shown's 5-key shape) through a wrapper validator,
--   2. adds the `seq` and `build` envelope columns and anon's insert grants,
--   3. recreates `events_clean` so it picks the two columns up, and
--   4. creates schema `analytics` with the views `orders`, `sessions` and
--      `visitors`, readable by the owner only.
--
-- STRICT SUPERSET (contract §4.1): #225's validator is kept whole under a
-- new name, `event_is_valid_225`, and the new `event_is_valid` decides only
-- the two new shapes and hands everything else to it unchanged. So every
-- (event_name, props) pair the store accepts on main is still accepted, by
-- the very same code. Cross-field invariants are still NOT checked in the
-- store (ADR 0007), except the one ADR 0014 records: fee_modes has as many
-- elements as restaurant_slugs.

-- 1a. Keep #225's validator, unchanged, under its own name. Renaming keeps
-- its body, owner and grants. Its execute grant is deliberately left as it
-- is: the RLS check below runs as the inserting role, so `anon` must still
-- be able to execute it through the wrapper (ADR 0013).
alter function public.event_is_valid(text, jsonb) rename to event_is_valid_225;

-- The wrapper (contract §4.4). Each new branch is guarded step by step
-- rather than in one `and` chain, because Postgres does not promise
-- short-circuit order and jsonb_array_length raises on a non-array. A
-- missing or mistyped value refuses the row: every check is wrapped in
-- coalesce, so null never passes.
create function public.event_is_valid(event_name text, props jsonb)
returns boolean
language plpgsql
immutable
as $$
declare
  keys text[];
begin
  select coalesce(array_agg(k order by k), array[]::text[])
    into keys
  from jsonb_object_keys(props) k;

  if event_name = 'order_placed' then
    if coalesce(public.event_is_valid_225(event_name, props), false) then
      return true;
    end if;
    -- The 15-key shape: #219's 14 keys plus restaurant_slug. Everything
    -- shared is checked by #225's code on the 14-key remainder.
    return coalesce(
      keys = array[
        'amount_minor', 'applied_voucher_ids', 'city', 'currency', 'delivery_instructions',
        'drop_off_preset', 'item_count', 'order_id', 'restaurant_slug', 'saved_amount_minor',
        'thanks_voucher_amount_minor', 'utensils', 'vip_level', 'vip_saved_amount_minor',
        'wallet_paid'
      ]
      and jsonb_typeof(props->'restaurant_slug') = 'string'
      and length(props->>'restaurant_slug') between 1 and 60
      and props->>'restaurant_slug' ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
      and public.event_is_valid_225(event_name, props - 'restaurant_slug'),
      false);

  elsif event_name = 'flash_sheet_shown' then
    if coalesce(public.event_is_valid_225(event_name, props), false) then
      return true;
    end if;
    -- The 5-key shape: the 4-key shape (5 or 6 distinct slugs, never the
    -- legacy 2) plus fee_modes, aligned by index with restaurant_slugs.
    if not coalesce(
      keys = array['amount_minor', 'city', 'currency', 'fee_modes', 'restaurant_slugs']
      and public.event_is_valid_225(event_name, props - 'fee_modes')
      and jsonb_array_length(props->'restaurant_slugs') in (5, 6)
      and jsonb_typeof(props->'fee_modes') = 'array',
      false) then
      return false;
    end if;
    return coalesce(
      jsonb_array_length(props->'fee_modes') = jsonb_array_length(props->'restaurant_slugs')
      and (
        select bool_and(jsonb_typeof(elem) = 'string' and (elem #>> '{}') in ('free', 'reduced'))
        from jsonb_array_elements(props->'fee_modes') elem
      ),
      false);
  end if;

  return public.event_is_valid_225(event_name, props);
end;
$$;

-- 1b. The policy was bound to the function itself, not its name, so after
-- the rename it calls `event_is_valid_225`. Recreate it against the
-- wrapper, with the same name, role and check expression ADR 0005 §2
-- records.
drop policy events_insert_anon on public.events;

create policy events_insert_anon on public.events
  for insert
  to anon
  with check (public.event_is_valid(event_name, props));

-- 2. The envelope (contract §5.1). Columns, not props, so they ride on
-- every event without changing any event's key set. Both are nullable with
-- no default: null means "sent by a client from before this pass" (R4),
-- never zero and never "unknown build". A CHECK passes a null, so an old
-- tab's insert is unaffected.
alter table public.events
  add column seq integer,
  add column build text;

alter table public.events
  add constraint events_seq_check check (seq between 1 and 100000),
  add constraint events_build_check check (build ~ '^[0-9a-f]{40}$' or build = '(unknown)');

grant insert (seq) on public.events to anon;
grant insert (build) on public.events to anon;

-- 3. `events_clean`, recreated so it exposes the new columns (a `select *`
-- view does not pick them up otherwise), with its definition unchanged: the
-- same `security_invoker` setting, the same exclusion of every visitor with
-- any `is_internal` row, and the same revokes as 20261002000000, since
-- Supabase grants anon and authenticated default privileges on every new
-- relation in `public`.
drop view public.events_clean;

create view public.events_clean
  with (security_invoker = true) as
  select e.*
  from public.events e
  where not exists (
    select 1
    from public.events flagged
    where flagged.visitor_id = e.visitor_id
      and flagged.is_internal
  );

revoke all on public.events_clean from anon;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on public.events_clean from authenticated';
  end if;
end
$$;

-- 4. Schema `analytics` (contract §11). Supabase's Data API exposes
-- `public` by default and not a new schema, and anon and authenticated get
-- no usage on this one, so a missed revoke on a view cannot publish it to
-- the browser. Every view reads only `public.events_clean` and other
-- `analytics` views (R1), so the owner-traffic exclusion holds for all of
-- them, and none reads `private`, `auth` or a wallet relation. Plain SQL
-- (CTEs and row_number(), `->` and `->>` only) so it lifts into dbt
-- unchanged. "First" is always the earliest by (received_at, id).
create schema analytics;

revoke all on schema analytics from public;
revoke all on schema analytics from anon;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on schema analytics from authenticated';
  end if;
end
$$;

-- 4a. One row per order_id with at least one order_placed row (§11.2).
create view analytics.orders
  with (security_invoker = true) as
with placed as (
  select
    e.visitor_id,
    e.session_id,
    e.occurred_at,
    e.received_at,
    e.build,
    e.props,
    row_number() over (partition by e.props->>'order_id' order by e.received_at, e.id) as rn,
    count(*) over (partition by e.props->>'order_id') as n
  from public.events_clean e
  where e.event_name = 'order_placed'
),
p as (
  select * from placed where rn = 1
),
first_delivered as (
  select order_id, received_at, props from (
    select e.props->>'order_id' as order_id, e.received_at, e.props,
      row_number() over (partition by e.props->>'order_id' order by e.received_at, e.id) as rn
    from public.events_clean e
    where e.event_name = 'order_delivered'
  ) x where rn = 1
),
first_rating as (
  select order_id, received_at, props from (
    select e.props->>'order_id' as order_id, e.received_at, e.props,
      row_number() over (partition by e.props->>'order_id' order by e.received_at, e.id) as rn
    from public.events_clean e
    where e.event_name = 'rating_submitted'
  ) x where rn = 1
),
first_driver_rating as (
  select order_id, received_at, props from (
    select e.props->>'order_id' as order_id, e.received_at, e.props,
      row_number() over (partition by e.props->>'order_id' order by e.received_at, e.id) as rn
    from public.events_clean e
    where e.event_name = 'driver_rating_submitted'
  ) x where rn = 1
),
first_tip as (
  select order_id, received_at, props from (
    select e.props->>'order_id' as order_id, e.received_at, e.props,
      row_number() over (partition by e.props->>'order_id' order by e.received_at, e.id) as rn
    from public.events_clean e
    where e.event_name = 'tip_sent'
  ) x where rn = 1
)
select
  (p.props->>'order_id')::uuid as order_id,
  p.visitor_id as visitor_id,
  p.session_id as session_id,
  p.received_at as placed_at,
  p.occurred_at as placed_occurred_at,
  (p.received_at at time zone 'UTC')::date as placed_day,
  p.build as build,
  case
    when p.props->'restaurant_slug' is not null then '#270'
    when p.props->'city' is not null then '#219'
    else '#81'
  end as props_shape,
  p.n::integer as placed_rows,
  coalesce(
    p.props->>'city',
    case p.props->>'currency' when 'VND' then 'hcmc' when 'USD' then 'sf' end
  ) as city,
  p.props->>'currency' as currency,
  p.props->>'restaurant_slug' as restaurant_slug,
  (p.props->>'amount_minor')::bigint as amount_minor,
  (p.props->>'item_count')::integer as item_count,
  p.props->'applied_voucher_ids' as applied_voucher_ids,
  jsonb_array_length(p.props->'applied_voucher_ids') as applied_voucher_count,
  (p.props->>'saved_amount_minor')::bigint as saved_amount_minor,
  (p.props->>'thanks_voucher_amount_minor')::bigint as thanks_voucher_amount_minor,
  p.props->>'vip_level' as vip_level,
  (p.props->>'vip_saved_amount_minor')::bigint as vip_saved_amount_minor,
  (p.props->>'wallet_paid')::boolean as wallet_paid,
  p.props->>'drop_off_preset' as drop_off_preset,
  p.props->>'delivery_instructions' as delivery_instructions,
  (p.props->>'utensils')::boolean as utensils,
  d.received_at as delivery_seen_at,
  r.received_at as restaurant_rated_at,
  (r.props->>'stars')::integer as restaurant_stars,
  dr.received_at as driver_rated_at,
  (dr.props->>'stars')::integer as driver_stars,
  t.received_at as tipped_at,
  (t.props->>'tip_amount_minor')::bigint as tip_amount_minor
from p
left join first_delivered d on d.order_id = p.props->>'order_id'
left join first_rating r on r.order_id = p.props->>'order_id'
left join first_driver_rating dr on dr.order_id = p.props->>'order_id'
left join first_tip t on t.order_id = p.props->>'order_id';

-- 4b. One row per session_id (a tab session, not a 30-minute visit) with
-- at least one row (§11.3).
create view analytics.sessions
  with (security_invoker = true) as
with agg as (
  select
    e.session_id,
    count(distinct e.visitor_id)::integer as visitor_ids,
    min(e.received_at) as started_at,
    max(e.received_at) as last_received_at,
    count(*)::integer as event_rows,
    (count(*) filter (where e.event_name = 'session_started'))::integer as session_started_rows,
    bool_or(e.event_name = 'order_placed') as ordered,
    (count(distinct e.props->>'order_id') filter (where e.event_name = 'order_placed'))::integer as orders,
    max(e.seq) as seq_max,
    count(distinct e.seq) as seq_count
  from public.events_clean e
  group by e.session_id
),
first_row as (
  select session_id, visitor_id from (
    select e.session_id, e.visitor_id,
      row_number() over (partition by e.session_id order by e.received_at, e.id) as rn
    from public.events_clean e
  ) x where rn = 1
),
ss as (
  select session_id, props from (
    select e.session_id, e.props,
      row_number() over (partition by e.session_id order by e.occurred_at, e.id) as rn
    from public.events_clean e
    where e.event_name = 'session_started'
  ) x where rn = 1
)
select
  agg.session_id as session_id,
  first_row.visitor_id as visitor_id,
  agg.visitor_ids as visitor_ids,
  agg.started_at as started_at,
  (agg.started_at at time zone 'UTC')::date as session_day,
  agg.last_received_at as last_received_at,
  agg.event_rows as event_rows,
  agg.session_started_rows as session_started_rows,
  case
    when ss.session_id is null then '(unknown)'
    when ss.props->>'utm_source' not in ('(none)', '(invalid)') then ss.props->>'utm_source'
    when ss.props->>'referrer_host' = '(self)' then '(self)'
    when ss.props->>'referrer_host' = '(invalid)' then '(invalid)'
    when ss.props->>'referrer_host' <> '(none)' then ss.props->>'referrer_host'
    else '(direct)'
  end as source,
  coalesce(ss.props->>'referrer_host', '(unknown)') as referrer_host,
  coalesce(ss.props->>'utm_source', '(unknown)') as utm_source,
  coalesce(ss.props->>'utm_medium', '(unknown)') as utm_medium,
  coalesce(ss.props->>'utm_campaign', '(unknown)') as utm_campaign,
  agg.ordered as ordered,
  agg.orders as orders,
  agg.seq_max as seq_max,
  case when agg.seq_max is null then null else agg.seq_count::integer end as seq_distinct,
  case when agg.seq_max is null then null else (agg.seq_max - agg.seq_count)::integer end as seq_lost
from agg
join first_row on first_row.session_id = agg.session_id
left join ss on ss.session_id = agg.session_id;

-- 4c. One row per visitor_id (a browser) with at least one row (§11.4).
create view analytics.visitors
  with (security_invoker = true) as
with agg as (
  select
    e.visitor_id,
    min(e.received_at) as first_seen_at,
    max(e.received_at) as last_seen_at,
    count(distinct (e.received_at at time zone 'UTC')::date)::integer as active_days,
    count(distinct e.session_id)::integer as sessions
  from public.events_clean e
  group by e.visitor_id
),
ft as (
  select visitor_id, session_id, received_at, props from (
    select e.visitor_id, e.session_id, e.received_at, e.props,
      row_number() over (partition by e.visitor_id order by e.occurred_at, e.id) as rn
    from public.events_clean e
    where e.event_name = 'session_started'
  ) x where rn = 1
),
o as (
  select visitor_id, count(*)::integer as orders
  from analytics.orders
  group by visitor_id
),
fo as (
  select visitor_id, order_id, placed_at from (
    select a.visitor_id, a.order_id, a.placed_at,
      row_number() over (partition by a.visitor_id order by a.placed_at, a.order_id) as rn
    from analytics.orders a
  ) x where rn = 1
)
select
  agg.visitor_id as visitor_id,
  agg.first_seen_at as first_seen_at,
  (agg.first_seen_at at time zone 'UTC')::date as first_seen_day,
  agg.last_seen_at as last_seen_at,
  agg.active_days as active_days,
  agg.sessions as sessions,
  ft.session_id as first_touch_session_id,
  ft.received_at as first_touch_at,
  case
    when ft.session_id is null then '(unknown)'
    when ft.props->>'utm_source' not in ('(none)', '(invalid)') then ft.props->>'utm_source'
    when ft.props->>'referrer_host' = '(self)' then '(self)'
    when ft.props->>'referrer_host' = '(invalid)' then '(invalid)'
    when ft.props->>'referrer_host' <> '(none)' then ft.props->>'referrer_host'
    else '(direct)'
  end as first_touch_source,
  coalesce(ft.props->>'referrer_host', '(unknown)') as first_touch_referrer_host,
  coalesce(ft.props->>'utm_source', '(unknown)') as first_touch_utm_source,
  coalesce(ft.props->>'utm_medium', '(unknown)') as first_touch_utm_medium,
  coalesce(ft.props->>'utm_campaign', '(unknown)') as first_touch_utm_campaign,
  coalesce(o.orders, 0) as orders,
  fo.order_id as first_order_id,
  fo.placed_at as first_order_at
from agg
left join ft on ft.visitor_id = agg.visitor_id
left join o on o.visitor_id = agg.visitor_id
left join fo on fo.visitor_id = agg.visitor_id;

-- Each view revoked from anon and authenticated, as events_clean is, and
-- granted to no one (§11.1).
revoke all on analytics.orders from anon;
revoke all on analytics.sessions from anon;
revoke all on analytics.visitors from anon;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    execute 'revoke all on analytics.orders from authenticated';
    execute 'revoke all on analytics.sessions from authenticated';
    execute 'revoke all on analytics.visitors from authenticated';
  end if;
end
$$;

commit;

-- Checks: every row should say PASS.
select n as "#", check_name, case when ok then 'PASS' else 'FAIL' end as result
from (values
  (1, 'events table, events_clean view and the two private rate-limit tables exist', (select count(*) from information_schema.tables where (table_schema, table_name) in
      (('public','events'),('public','events_clean'),('private','write_log'),('private','rate_limit_salt'))) = 4),
  (2, 'the rate-limit salt has exactly one row', (select count(*) from private.rate_limit_salt) = 1),
  (3, 'the rate-limit trigger can find the hashing function (extensions on its search_path)', (select array_to_string(proconfig, ',') like '%extensions%' from pg_proc where proname = 'enforce_write_rate_limit')),
  (4, 'the readiness events are accepted (driver_rating_submitted)', (select pg_get_functiondef('public.event_is_valid_224(text, jsonb)'::regprocedure) like '%driver_rating_submitted%')),
  (5, 'session_started is accepted', (select pg_get_functiondef('public.event_is_valid_225(text, jsonb)'::regprocedure) like '%session_started%')),
  (6, 'is_internal column: boolean, not null, default false', exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'events'
      and column_name = 'is_internal' and data_type = 'boolean' and is_nullable = 'NO' and column_default = 'false')),
  (7, 'seq (integer) and build (text) columns exist and are optional', (select count(*) from information_schema.columns where table_schema = 'public' and table_name = 'events'
      and ((column_name = 'seq' and data_type = 'integer') or (column_name = 'build' and data_type = 'text'))
      and is_nullable = 'YES' and column_default is null) = 2),
  (8, 'the second-pass shapes are accepted (fee_modes)', (select pg_get_functiondef('public.event_is_valid(text, jsonb)'::regprocedure) like '%fee_modes%')),
  (9, 'analytics views exist and the public key cannot read them', not has_table_privilege('anon', 'analytics.orders', 'select') and (select count(*) from analytics.orders) >= 0),
  (10, 'the public key cannot read raw events', not has_table_privilege('anon', 'public.events', 'select'))
) as checks(n, check_name, ok)
order by n;
