-- Play-money wallet: the three wallet migrations (ADR 0008 owner setup, step 12). Only when switching the wallet on.
--
-- GENERATED by scripts/build-setup-sql.mjs from supabase/migrations/. Do not edit.
-- Paste the whole file into Supabase > SQL Editor > New query, and click Run once.
-- Everything runs in one transaction: if any statement fails, nothing is
-- applied, and the file can be run again after the problem is fixed.
-- The last result is a table of checks. Every row should say PASS.

begin;

-- ============================================================
-- 20260927000000_wallet.sql
-- ============================================================
-- #145: additive migration for the play-money wallet — ADR 0008
-- (docs/decisions/0008-play-money-wallet-and-sign-in.md), objective #136.
-- Strictly additive per house rules: this file only creates new relations
-- and functions; 20260925000000_events.sql and
-- 20260926000000_two_city_event_contract.sql are untouched, and the
-- `events` table's grants are unchanged.
--
-- Assumes `auth.users`, `auth.uid()` and the `authenticated` role exist, as
-- they do on Supabase. Never creates or replaces any of the three — the
-- test suite stubs them first (wallet.migration.test.ts), and a
-- `create or replace function auth.uid()` here would overwrite Supabase's
-- own function on the live project. `private` is the schema
-- 20260925000000_events.sql already created.
--
-- All amounts are integer minor units: cents for USD, whole đồng for VND
-- (src/lib/money.ts).

create table public.wallets (
  user_id uuid primary key references auth.users (id) on delete cascade,
  usd_minor bigint not null check (usd_minor >= 0),
  vnd_minor bigint not null check (vnd_minor >= 0),
  created_at timestamptz not null default now()
);

-- RLS is enabled but not forced, so the security-definer functions below
-- (owned by the table owner) can still write it — deliberately different
-- from `events`, which is force-RLS'd because nothing writes it but anon's
-- own insert.
alter table public.wallets enable row level security;

create policy wallets_select_own on public.wallets
  for select
  to authenticated
  using (user_id = (select auth.uid()));

-- No client role can insert, update or delete a wallet directly. Only the
-- functions below change it.
revoke all on public.wallets from anon, authenticated;
grant select on public.wallets to authenticated;

-- The key is what makes "one claim per window" a database fact.
create table private.wallet_claims (
  user_id uuid not null references auth.users (id) on delete cascade,
  window_start timestamptz not null,
  claimed_at timestamptz not null default now(),
  primary key (user_id, window_start)
);

-- The key is the idempotency key for wallet_debit.
create table private.wallet_debits (
  order_id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  currency text not null check (currency in ('USD', 'VND')),
  amount_minor bigint not null check (amount_minor > 0),
  debited_at timestamptz not null default now()
);

-- Private helpers. No grant to anon or authenticated: the Data API doesn't
-- expose the `private` schema at all, and the default PUBLIC execute grant
-- Postgres gives every new function is revoked below on each one, so even a
-- direct connection as anon/authenticated is refused.

-- The preload happens exactly once per account, on whichever wallet call
-- comes first. There is no trigger on auth.users (rejected alternative,
-- ADR 0008): a failing trigger fails the sign-up itself.
create or replace function private.ensure_wallet(p_user_id uuid)
returns void
language plpgsql
set search_path = ''
as $$
begin
  insert into public.wallets (user_id, usd_minor, vnd_minor)
  values (p_user_id, 3000, 750000)
  on conflict (user_id) do nothing;
end;
$$;

revoke execute on function private.ensure_wallet(uuid) from public;

-- D8's floor, hard-coded. SF's cheapest item is 300 and its lowest delivery
-- fee is 99 (src/lib/restaurants.ts); HCMC's are 10,000 and 10,000. The
-- floor is safe for legitimate orders today: the smallest real totals are
-- 450 cents in SF and 30,000 ₫ in HCMC.
create or replace function private.debit_floor_minor(p_currency text)
returns bigint
language sql
immutable
set search_path = ''
as $$
  select case p_currency
    when 'USD' then 399::bigint
    when 'VND' then 20000::bigint
  end;
$$;

revoke execute on function private.debit_floor_minor(text) from public;

-- The windows are local America/Los_Angeles time: [07:00, 15:00),
-- [15:00, 23:00) and [23:00, 07:00), each half-open. `date_trunc('day', ...)`
-- gives local midnight as a naive timestamp; subtracting one hour from it is
-- yesterday's 23:00, which is what makes the "before 07:00" branch below
-- work without a separate day-rollback case. Converting a naive local
-- wall-clock timestamp back with `at time zone` looks up that zone's offset
-- for that specific local time, so the DST transition is handled by
-- Postgres's own zoneinfo rather than by any date arithmetic here — this
-- function must stay `stable`, not `immutable`, because it depends on
-- `America/Los_Angeles`'s zoneinfo rules.
create or replace function private.drip_window_start(p_at timestamptz)
returns timestamptz
language sql
stable
set search_path = ''
as $$
  select (
    date_trunc('day', p_at at time zone 'America/Los_Angeles')
    + case
        when (p_at at time zone 'America/Los_Angeles')::time >= time '23:00' then interval '23 hours'
        when (p_at at time zone 'America/Los_Angeles')::time >= time '15:00' then interval '15 hours'
        when (p_at at time zone 'America/Los_Angeles')::time >= time '07:00' then interval '7 hours'
        else interval '-1 hours'
      end
  ) at time zone 'America/Los_Angeles';
$$;

revoke execute on function private.drip_window_start(timestamptz) from public;

-- Adds 8 nominal local wall-clock hours to the current window's start,
-- then converts back the same way `drip_window_start` does — so a DST
-- transition inside those 8 local hours changes the real elapsed time
-- (7 or 9 hours) without changing the wall-clock boundary.
create or replace function private.drip_next_window_start(p_at timestamptz)
returns timestamptz
language sql
stable
set search_path = ''
as $$
  select (
    (private.drip_window_start(p_at) at time zone 'America/Los_Angeles') + interval '8 hours'
  ) at time zone 'America/Los_Angeles';
$$;

revoke execute on function private.drip_next_window_start(timestamptz) from public;

-- The internal, clock-taking engine behind wallet_claim_drip. No client
-- role can execute this — the client-callable function below always passes
-- it now(). Tests exercise drip windows (including the DST cases) by
-- calling this directly as the table owner, which bypasses grants entirely.
create or replace function private.wallet_claim_drip_at(p_user_id uuid, p_at timestamptz)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_window_start timestamptz := private.drip_window_start(p_at);
  v_claimed boolean := false;
  v_usd_minor bigint;
  v_vnd_minor bigint;
begin
  perform private.ensure_wallet(p_user_id);

  insert into private.wallet_claims (user_id, window_start)
  values (p_user_id, v_window_start)
  on conflict (user_id, window_start) do nothing;

  if found then
    v_claimed := true;
    update public.wallets
      set usd_minor = usd_minor + 500,
          vnd_minor = vnd_minor + 100000
      where user_id = p_user_id;
  end if;

  select w.usd_minor, w.vnd_minor into v_usd_minor, v_vnd_minor
  from public.wallets w
  where w.user_id = p_user_id;

  return jsonb_build_object(
    'claimed', v_claimed,
    'usd_minor', v_usd_minor,
    'vnd_minor', v_vnd_minor,
    'window_start', v_window_start,
    'next_window_start', private.drip_next_window_start(p_at)
  );
end;
$$;

revoke execute on function private.wallet_claim_drip_at(uuid, timestamptz) from public;

-- Public wallet functions. Every one is security definer (wallet_ready is
-- the sole exception — it reads nothing), set search_path = '' with every
-- relation schema-qualified, stripped of the default grants Supabase and
-- Postgres both hand new public functions to PUBLIC by default, and
-- granted back only to the role named here. Each runs as one transaction
-- per call (one PostgREST request).

create or replace function public.wallet_ready()
returns boolean
language sql
stable
set search_path = ''
as $$
  select true;
$$;

revoke all on function public.wallet_ready() from public;
grant execute on function public.wallet_ready() to anon, authenticated;

create or replace function public.wallet_get()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_now timestamptz := now();
  v_usd_minor bigint;
  v_vnd_minor bigint;
  v_claimed boolean;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;
  if coalesce((current_setting('request.jwt.claims', true)::jsonb ->> 'is_anonymous')::boolean, false) then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  perform private.ensure_wallet(v_user_id);

  select w.usd_minor, w.vnd_minor into v_usd_minor, v_vnd_minor
  from public.wallets w
  where w.user_id = v_user_id;

  select exists (
    select 1 from private.wallet_claims c
    where c.user_id = v_user_id and c.window_start = private.drip_window_start(v_now)
  ) into v_claimed;

  return jsonb_build_object(
    'usd_minor', v_usd_minor,
    'vnd_minor', v_vnd_minor,
    'window_start', private.drip_window_start(v_now),
    'next_window_start', private.drip_next_window_start(v_now),
    'claimed_this_window', v_claimed
  );
end;
$$;

revoke all on function public.wallet_get() from public;
grant execute on function public.wallet_get() to authenticated;

create or replace function public.wallet_claim_drip()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;
  if coalesce((current_setting('request.jwt.claims', true)::jsonb ->> 'is_anonymous')::boolean, false) then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  return private.wallet_claim_drip_at(v_user_id, now());
end;
$$;

revoke all on function public.wallet_claim_drip() from public;
grant execute on function public.wallet_claim_drip() to authenticated;

-- wallet_debit checks, in order: authenticated and not anonymous; currency
-- is USD or VND; amount is positive; amount clears the floor; then the
-- order_id idempotency key — a hit belonging to the caller returns
-- already_debited unchanged, a hit belonging to someone else raises. Only
-- then is the wallet locked and the balance checked, so a JSON-shaped
-- browser amount can never mint money, double-charge one order, or read or
-- change another user's wallet (ADR 0008, "fully guarded" list).
create or replace function public.wallet_debit(p_order_id uuid, p_currency text, p_amount_minor bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_existing private.wallet_debits%rowtype;
  v_usd_minor bigint;
  v_vnd_minor bigint;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;
  if coalesce((current_setting('request.jwt.claims', true)::jsonb ->> 'is_anonymous')::boolean, false) then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  if p_currency not in ('USD', 'VND') then
    raise exception 'invalid_currency' using errcode = '22023';
  end if;

  if p_amount_minor <= 0 then
    raise exception 'invalid_amount' using errcode = '22023';
  end if;

  if p_amount_minor < private.debit_floor_minor(p_currency) then
    raise exception 'below_floor' using errcode = '22023';
  end if;

  select * into v_existing from private.wallet_debits where order_id = p_order_id;

  if found then
    if v_existing.user_id <> v_user_id then
      raise exception 'order_id_conflict' using errcode = '23505';
    end if;

    perform private.ensure_wallet(v_user_id);

    select w.usd_minor, w.vnd_minor into v_usd_minor, v_vnd_minor
    from public.wallets w
    where w.user_id = v_user_id;

    return jsonb_build_object(
      'status', 'already_debited',
      'usd_minor', v_usd_minor,
      'vnd_minor', v_vnd_minor,
      'next_window_start', private.drip_next_window_start(now())
    );
  end if;

  perform private.ensure_wallet(v_user_id);

  select w.usd_minor, w.vnd_minor into v_usd_minor, v_vnd_minor
  from public.wallets w
  where w.user_id = v_user_id
  for update;

  if (p_currency = 'USD' and v_usd_minor < p_amount_minor)
    or (p_currency = 'VND' and v_vnd_minor < p_amount_minor) then
    return jsonb_build_object(
      'status', 'insufficient',
      'usd_minor', v_usd_minor,
      'vnd_minor', v_vnd_minor,
      'next_window_start', private.drip_next_window_start(now())
    );
  end if;

  if p_currency = 'USD' then
    update public.wallets set usd_minor = usd_minor - p_amount_minor where user_id = v_user_id;
    v_usd_minor := v_usd_minor - p_amount_minor;
  else
    update public.wallets set vnd_minor = vnd_minor - p_amount_minor where user_id = v_user_id;
    v_vnd_minor := v_vnd_minor - p_amount_minor;
  end if;

  insert into private.wallet_debits (order_id, user_id, currency, amount_minor)
  values (p_order_id, v_user_id, p_currency, p_amount_minor);

  return jsonb_build_object(
    'status', 'debited',
    'usd_minor', v_usd_minor,
    'vnd_minor', v_vnd_minor,
    'next_window_start', private.drip_next_window_start(now())
  );
end;
$$;

revoke all on function public.wallet_debit(uuid, text, bigint) from public;
grant execute on function public.wallet_debit(uuid, text, bigint) to authenticated;

-- ============================================================
-- 20260928000000_wallet_tip.sql
-- ============================================================
-- #164: additive migration for tipping a driver from the wallet — ADR 0008
-- amendment (docs/decisions/0008-play-money-wallet-and-sign-in.md), objective
-- #135, presets from #162 (docs/design/162-rating-win-tips-rewards-vip.md).
-- Strictly additive per house rules: this file only creates new relations
-- and functions; 20260925000000_events.sql, 20260926000000_two_city_event_
-- contract.sql and 20260927000000_wallet.sql are untouched, and none of
-- their grants change.
--
-- A tip cannot reuse wallet_debit: wallet_debits is keyed by order_id, so a
-- tip on an already-debited order would return already_debited and charge
-- nothing, and wallet_debit's floor (399 cents / 20.000 VND) would reject
-- most plausible tips. Tips are their own idempotency key, their own table,
-- and their own fixed presets the server enforces exactly (D14, #162).
--
-- All amounts are integer minor units: cents for USD, whole đồng for VND
-- (src/lib/money.ts).

-- The key is the idempotency key for wallet_tip: one tip per order. The
-- foreign key to wallet_debits.order_id is D14 as a database fact — a tip
-- cannot exist for an order that was never paid from the wallet.
create table private.wallet_tips (
  order_id uuid primary key references private.wallet_debits (order_id),
  user_id uuid not null references auth.users (id) on delete cascade,
  currency text not null check (currency in ('USD', 'VND')),
  amount_minor bigint not null check (amount_minor > 0),
  tipped_at timestamptz not null default now()
);

-- private has no USAGE grant to anon or authenticated (ADR 0008, "private is
-- the schema ADR 0005's migration already created... anon and authenticated
-- have no usage on it") — a new table in it needs no explicit revoke, the
-- same as wallet_debits above. Stated as a check below, not just an
-- assumption.

-- The tip presets, hard-coded exactly as the driver accepted them on #164:
-- USD 100/200/300 cents, VND 10000/20000/30000 đồng. Any other amount is
-- refused. immutable and takes no time argument, so it is safe even if a
-- future change ever exposed it.
create or replace function private.is_valid_tip_amount(p_currency text, p_amount_minor bigint)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select case p_currency
    when 'USD' then p_amount_minor in (100, 200, 300)
    when 'VND' then p_amount_minor in (10000, 20000, 30000)
    else false
  end;
$$;

revoke execute on function private.is_valid_tip_amount(text, bigint) from public;

-- public.wallet_tip: tips the order's own driver, once per order_id, for
-- exactly one of the caller's currency's presets. security definer, fixed
-- search_path, stripped of PUBLIC's default execute grant, granted only to
-- authenticated (ADR 0008's function template, "Functions").
--
-- Checks, in order:
-- 1. auth.uid() is not null, and the caller is not an anonymous-auth user.
-- 2. order_id has a wallet_debits row at all, and it belongs to the caller
--    (D14) — refused otherwise, so tipping is only ever the caller's own
--    paid order, never an unpaid or someone else's order.
-- 3. The currency comes from that debit row, never from the caller, and the
--    amount is one of that currency's presets — anything else is refused.
-- 4. order_id idempotency: an existing tip returns already_tipped with the
--    original amount unchanged, rather than raising, so a retrying client
--    gets a normal answer instead of an error to unpack.
-- 5. Only then is the wallet locked and the balance checked: insufficient
--    leaves it unchanged, otherwise the tip is debited and recorded in the
--    same transaction.
create or replace function public.wallet_tip(p_order_id uuid, p_amount_minor bigint)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_debit private.wallet_debits%rowtype;
  v_existing_tip private.wallet_tips%rowtype;
  v_usd_minor bigint;
  v_vnd_minor bigint;
begin
  v_user_id := auth.uid();
  if v_user_id is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;
  if coalesce((current_setting('request.jwt.claims', true)::jsonb ->> 'is_anonymous')::boolean, false) then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  select * into v_debit from private.wallet_debits where order_id = p_order_id;

  if not found then
    raise exception 'order_not_debited' using errcode = '22023';
  end if;

  if v_debit.user_id <> v_user_id then
    raise exception 'order_not_debited' using errcode = '22023';
  end if;

  if not private.is_valid_tip_amount(v_debit.currency, p_amount_minor) then
    raise exception 'invalid_tip_amount' using errcode = '22023';
  end if;

  select * into v_existing_tip from private.wallet_tips where order_id = p_order_id;

  if found then
    perform private.ensure_wallet(v_user_id);

    select w.usd_minor, w.vnd_minor into v_usd_minor, v_vnd_minor
    from public.wallets w
    where w.user_id = v_user_id;

    return jsonb_build_object(
      'status', 'already_tipped',
      'amount_minor', v_existing_tip.amount_minor,
      'currency', v_existing_tip.currency,
      'usd_minor', v_usd_minor,
      'vnd_minor', v_vnd_minor
    );
  end if;

  perform private.ensure_wallet(v_user_id);

  select w.usd_minor, w.vnd_minor into v_usd_minor, v_vnd_minor
  from public.wallets w
  where w.user_id = v_user_id
  for update;

  if (v_debit.currency = 'USD' and v_usd_minor < p_amount_minor)
    or (v_debit.currency = 'VND' and v_vnd_minor < p_amount_minor) then
    return jsonb_build_object(
      'status', 'insufficient',
      'usd_minor', v_usd_minor,
      'vnd_minor', v_vnd_minor
    );
  end if;

  if v_debit.currency = 'USD' then
    update public.wallets set usd_minor = usd_minor - p_amount_minor where user_id = v_user_id;
    v_usd_minor := v_usd_minor - p_amount_minor;
  else
    update public.wallets set vnd_minor = vnd_minor - p_amount_minor where user_id = v_user_id;
    v_vnd_minor := v_vnd_minor - p_amount_minor;
  end if;

  insert into private.wallet_tips (order_id, user_id, currency, amount_minor)
  values (p_order_id, v_user_id, v_debit.currency, p_amount_minor);

  return jsonb_build_object(
    'status', 'tipped',
    'amount_minor', p_amount_minor,
    'currency', v_debit.currency,
    'usd_minor', v_usd_minor,
    'vnd_minor', v_vnd_minor
  );
end;
$$;

revoke all on function public.wallet_tip(uuid, bigint) from public;
grant execute on function public.wallet_tip(uuid, bigint) to authenticated;

-- ============================================================
-- 20260929000000_wallet_revoke_anon_execute.sql
-- ============================================================
-- #188: additive migration closing a privilege hole in the wallet functions
-- — ADR 0008 (docs/decisions/0008-play-money-wallet-and-sign-in.md, lines
-- 123 and 273), objective #186.
-- Strictly additive per house rules: this file only revokes grants;
-- 20260925000000_events.sql, 20260926000000_two_city_event_contract.sql,
-- 20260927000000_wallet.sql and 20260928000000_wallet_tip.sql are untouched.
--
-- Supabase grants `execute` on every new `public` function to `anon` and
-- `authenticated` directly, through its own default privileges, not only
-- through the `PUBLIC` pseudo-role. `20260927000000_wallet.sql` and
-- `20260928000000_wallet_tip.sql` only run `revoke all ... from public`
-- (and `revoke execute ... from public`) on these four functions before
-- granting execute back to `authenticated` alone — revoking `PUBLIC`'s own
-- grant never touches a grant already made directly to a named role, so on
-- the live database `anon` still holds execute on all four. ADR 0008 called
-- for `revoke execute ... from public, anon`; only the `public` half ever
-- shipped.
--
-- `public.wallet_ready()` is deliberately excluded: it must stay
-- executable by `anon` (D1's fallback, #140) — it is the "is the wallet
-- configured?" probe that runs for signed-out visitors, and revoking it
-- would break checkout for every one of them.

revoke execute on function public.wallet_get() from anon;
revoke execute on function public.wallet_claim_drip() from anon;
revoke execute on function public.wallet_debit(uuid, text, bigint) from anon;
revoke execute on function public.wallet_tip(uuid, bigint) from anon;

commit;

-- Checks: every row should say PASS.
select n as "#", check_name, case when ok then 'PASS' else 'FAIL' end as result
from (values
  (1, 'wallets table exists', exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'wallets')),
  (2, 'wallet functions exist', (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'public' and p.proname in ('wallet_get','wallet_claim_drip','wallet_debit','wallet_tip')) = 4),
  (3, 'the public key cannot call wallet functions (#217)', not has_function_privilege('anon', 'public.wallet_debit(uuid, text, bigint)', 'execute')
      and not has_function_privilege('anon', 'public.wallet_tip(uuid, bigint)', 'execute')),
  (4, 'signed-in users can call wallet functions', has_function_privilege('authenticated', 'public.wallet_debit(uuid, text, bigint)', 'execute'))
) as checks(n, check_name, ok)
order by n;
